### ISSUE TITLE
UI issues in Getting Started tutorial prevent things from working 

### ISSUE THREAD

**Issue by harimohanraj** [slackapi/bolt-python#1014]
This is difficult to reproduce, but basically I ran into some issues where selecting options in the app configuration UI were not persisted even after selecting "Save Changes" or hitting a toggle, leading to messages *not* being sent to my bot running locally using SocketHandlerMode. 

Specifically, enabling Socket mode was not persisted, and turning on Event Subscriptions was not persisted (even though I could enable it and hit "Save Changes"! It was not really clear what was happening or why things weren't working, as no errors were showing up in the terminal or the browser. 

It finally just worked after I deleted my app and tried again, but not really clear why! 

Just wanted to give a heads up that there might be some issues there.

**Comment by seratch** [comment]
Hi @harimohanraj, thank you so much for taking the time to write in here, and we're sorry about the disruption you've experienced. As you observed, there might be certain technical issues with the app configuration pages at that time. Since I don't have any information about this issue so far, I will check this with our internal teams if there were any such issues. If affirmed, our engineering teams will imporove operations to prevent such problems in the future.
