### ISSUE TITLE
Error in chat_postMessage method just for send images

### ISSUE THREAD

**Issue by soilmo** [slackapi/bolt-python#1018]
Hi!

I am facing a problem to send image from slack cloud. The same problem was solved at past week with help of @filmaj :)

![image](https://github.com/slackapi/bolt-python/assets/60858896/2c0e76b3-1181-4233-9266-843fbea4c903)

My message with image is send using method say and block. The code is bellow:

![image](https://github.com/slackapi/bolt-python/assets/60858896/be9998d4-15e2-4d35-8ce2-e97202116171)

Where infos[0] = "https://files.slack.com/files-pri/T01J6BY2VEU-F06EYTKJAJX/rentabilidades.png?pub_secret=bb2f7a0d27"

To complement, i used User Oauth Token to upload image.

![image](https://github.com/slackapi/bolt-python/assets/60858896/f5a6a2a2-0062-49cb-9146-66226b2b3eac)

**Comment by filmaj** [comment]
@soilmo hello again 👋 

We decided to move ahead with rolling out file-backed image support, which would break the approach you are currently using. In the end, reverse-engineering images uploaded to Slack and their public URLs - including public access tokens - is not an official supported way documented by Slack. It looks to me like you used [this StackOverflow answer](https://stackoverflow.com/a/57254520/224514).

Please try the following:
- use the same token to upload the file and to post the message
- change your `blocks` payload to:

```
blocks = [{
  "type": "image",
  "title": {
    "type": "plain_text",
    "text": "This image block contains a reference to a Slack image file."
  },
  "block_id": "image4",
  "slack_file": {
    "id": "F0123456", // <-- get this from the response to the file upload
  },
  "alt_text": "Slack file object."
}]
```

**Comment by soilmo** [comment]
@filmaj Thanks for the suggestion!

I tried by the following block:

![image](https://github.com/slackapi/bolt-python/assets/60858896/e7db68dd-8b2e-433b-928d-bd942b5383b3)

Where infos[0] = "F06EW9V4V0V"

This id was got by:

![image](https://github.com/slackapi/bolt-python/assets/60858896/5ef0ef9a-8601-4f65-acf8-41c8beebb149)

After this attempt, i got the error bellow:

![image](https://github.com/slackapi/bolt-python/assets/60858896/5d2fdefe-6c3c-4384-ad05-240602a1a3d3)

Can you help with this?

**Comment by filmaj** [comment]
So you are uploading with a user token but are using `say`, which uses the bot token. Try using the same token for both operations.

**Comment by soilmo** [comment]
Nice!

I configured like that:

![image](https://github.com/slackapi/bolt-python/assets/60858896/5c1b7666-cdcb-4c44-8545-2dd27cf454cd)

Uploading the image:

![image](https://github.com/slackapi/bolt-python/assets/60858896/71fa84ee-b48d-4413-ac51-8175dcc34f60)

In this attempt, I understand the i am using the same token for uploading and sending image.

**Comment by filmaj** [comment]
That's correct. Did it resolve your issue?

**Comment by soilmo** [comment]
No :(

With these settings, i got a new error:

![image](https://github.com/slackapi/bolt-python/assets/60858896/a315ece3-0367-4d92-bfa6-af44020cef94)

I suppose the error occurs at line the following line, something related with channel_id:

![image](https://github.com/slackapi/bolt-python/assets/60858896/f48ef692-cae8-4bfa-9b64-00bffb84432b)

Because print isn't printed. To support your knowledge my parameter channel_id is a channel id of a private chat of a specific user.

**Comment by filmaj** [comment]
Ah yes so that makes sense. The bot is not a part of the private chat so the channel is unknown to the bot.

Can you explain your use case? What are you trying to accomplish? Where do you want to post the message w/ `blocks` that contain the uploaded file - to a private DM or to a public channel?

**Comment by soilmo** [comment]
Sure!

I build a bot that answer private chat for each user in my company. So, for each user, bot has a specific channel id.

My problem is just about sending images/files and to answer private DM.

I think that a change parameter channel_id, i will solve this case. But i dont know what channel_it to use kkkkk

```
client = WebClient(token=SLACK_BOT_TOKEN)
result = client.files_upload(channel=channel_id,file=path, initial_comment = 'Rentabilidades')
```

**Comment by filmaj** [comment]
So your bot is a member of a private chat (DM) with each user, yes? Does this private chat exist at the time of file uploading?

If my following assumptions are true:

- a private DM exists between the user and the bot and already has at least 1 message between the bot and the user
- the bot is to post a message to the private DM that includes the uploaded file as part of its blocks

Then, you should be able to:
1. Call `files_upload` using the bot token and removing the `channel` argument. This makes the file 'private' to the bot - it will not be automatically shared to any channel. For context: calling `files_upload` with the `channel` automatically shares the file on-upload to the provided channel and makes the file shareable.
2. Call `post_message` or `say` with a `blocks` argument that contains an image block with the `slack_file.id` argument pointing to the uploaded file. As of a few days ago, we support setting image block source to be a private, unshared file uploaded to Slack.

**Comment by soilmo** [comment]
Got it!

I just remove channel argument in files_upload.

**Comment by soilmo** [comment]
It works! Thanks!

About send HTML ou Excel files, how can i do that?

**Comment by filmaj** [comment]
> About send HTML ou Excel files, how can i do that?

As part of a message within Slack? It should be similar: upload a file and include a link to the file in the message you create. However, please remember the details around both file permissions and channel membership: by default, when you upload a file using `files_upload` and DO NOT include the `channel` parameter, then the file won't be viewable/visible by other users.

The following screenshot is an example of what I mean. In the screenshot, there are two users in a public channel, my app (`BoltJsApp`) and my user `filmaj2`. First, my bot uploaded a file WITHOUT the `channel` parameter. As my own user and not as the bot user, I posted the `permalink` of the uploaded file. You can see that in that first message from `filmaj2`, the file did not display! This is because the file is first private - only viewable by the user who uploaded it (the app user `BoltJsApp`).

<img width="707" alt="Screenshot 2024-01-22 at 12 01 00 PM" src="https://github.com/slackapi/bolt-python/assets/52645/61ad6b44-cb91-4c7d-b131-c4a0d1f9c8a9">

However, I then posted the exact same message text _as the bot user_, which _does have access to the (initially private) uploaded file_. The image unfurled in that message! This is because the file has now become 'viewable' by everyone in this Slack workspace - it is no longer private, because a link to the private file was shared by the owner of the file within Slack. Now anyone can see it - and you can see too, if I post the same message as my own user `filmaj2` with a link to the file, it now unfurls and displays without issue:

<img width="706" alt="Screenshot 2024-01-22 at 12 03 19 PM" src="https://github.com/slackapi/bolt-python/assets/52645/b9213881-8066-446a-a599-70f2e134ed8f">

I hope that helps explain the details for file permissions, uploading process and sharing files within Slack.

If that solves your problem, please kindly close the issue.

Good luck and happy coding!

**Comment by soilmo** [comment]
Thanks for answer!

It help me, but not completely.

Suppose you have a HTML file or Excel file and you would like to send it as a embedded link in a message. Like a "download message". I tried pass this "direct_link" in text answer, but doesn't work.

Following you can see steps:

![image](https://github.com/slackapi/bolt-python/assets/60858896/8f293341-d235-4dd1-ba70-1a4789d1743f)

And to send, i did like this:

![image](https://github.com/slackapi/bolt-python/assets/60858896/47a20375-27a9-4db9-bf60-084088f7b2ca)

The answer worked well, but link sent dont make download of file.

**Comment by filmaj** [comment]
You are seeing the same permission issue as before: after you upload the file, it is not viewable/shareable until the owner of the file (the bot) shares the `permalink` of the file in a public channel. After that, you can use the `url_private_download` link as a direct link to download the file.

**Comment by soilmo** [comment]
Good job!!

Thanks a lot! It's done!

**Comment by filmaj** [comment]
Great! I will close this issue then.
