### ISSUE TITLE
Unexpected EOF while reading bytes

### ISSUE THREAD

**Issue by ashutosh-ag-2024** [slackapi/bolt-python#1031]
#### The `slack_bolt` version

slack-bolt==1.18.0
slack_sdk==3.26.2

#### Python runtime version

Python 2.7.5

#### OS info

Ubuntu 20.04

#### Steps to reproduce:

Running a normal slack app which sends message in the form of blocks and receives input on submit button click.
Everything runs normally but in logs there is this below warning, what does this signify and can it cause issues ?

2024-02-20 13:18:42:WARNING: Error on \<machine-ip\>:9000 ping: Unexpected EOF while reading bytes
2024-02-20 13:18:42:WARNING: Connection was closed, reconnecting.
2024-02-20 13:18:42:WARNING: Error on socket shutdown: [Errno 107] Transport endpoint is not connected

**Comment by srajiang** [comment]
@ashutosh-ag-2024 - When does this error occur? Does it occur consistently? Does it impact your app functioning?

**Comment by seratch** [comment]
This warning might be raised by the underlying modules such as Python standard libraries and WebSocket client libraries. If you see the warnings frequently, that may be caused by the network stability and/or some issues with proxy servers. 

Enabling debug-level logging might be helpful to know more details, but if there is no issue affecting your end-users and you're observing the warnings in app logs, you can ignore it so far.
