### ISSUE TITLE
Slack Bot works in my workspace, but doesn't respond when Installed elsewhere

### ISSUE THREAD

**Issue by MarianBzz** [slackapi/bolt-python#1050]
When attempting to install the Slack bot developed in my workspace into other workspaces, I encounter difficulties in getting it to function correctly, despite accepting the necessary permissions during the installation process.

I've developed a Slack bot using Socket Mode to enable its integration into different workspaces. While the bot performs flawlessly in my workspace following installation and initial setup, I've faced challenges when attempting to replicate its functionality in other workspaces. Despite completing the installation process successfully, the bot fails to respond to commands or execute its intended functionalities.

Steps Taken:

1. Configured the Slack bot in my workspace following Slack's provided documentation.
2. Generated required credentials and configured permissions for the bot.
3. Installed the bot in other workspaces, adhering to the same procedures followed in my workspace, and accepting all necessary permissions during installation.
4. Despite successful installation, the bot does not respond to commands or perform expected tasks in other workspaces.

Could it be possible to utilize the app in other workspaces with its functionalities while keeping the Socket Mode activated, or should I consider migrating to HTTP? Alternatively, what might be the reason behind its malfunctioning in other workspaces?

Configuration Details:
![image](https://github.com/slackapi/bolt-python/assets/100612722/3f915783-9e18-480e-a663-da018432e9c8)

![image](https://github.com/slackapi/bolt-python/assets/100612722/85209fee-b3de-4453-a9b1-22ed6f318b30)

**Comment by WilliamBergamin** [comment]
Hi @MarianBzz thanks for writing in 💯 

Have you implemented [OAuth](https://api.slack.com/authentication/oauth-v2)?
In order to install your application in multiple workspaces ([distribution](https://api.slack.com/start/distributing#multi_workspace_apps)), your app needs to be able to store/handle a `bot_token` for each workspace it is installed in

Here is an example of [OAuth and socket mode](https://github.com/slackapi/bolt-python/blob/main/examples/socket_mode_oauth.py)
