### ISSUE TITLE
@app_mention event is not being triggered sometimes

### ISSUE THREAD

**Issue by TALUPURI-DIMPLE-HIMA-BINDU** [slackapi/bolt-python#1070]
We are using our slack app by doing @app_mention from workflow message .
In most cases the app_mention wrks as expected but in some instances we see that the app_mention doesn't trigger. We thought it's a backend error from our side but it seems like the app_mention is not happening at all for some cases. 
Does this happen when multiple events trigger simultaneously if so how to handle it . 

The events  we are triggering are :
1. @app_mention
2. Some button actions 
    total 3 different button actions.
    
We are using app in 5 different channels simultaneously ,  and for each request an app_mention is triggered and other events as well . Is this happening due simultaneous events being triggered ?

**Comment by seratch** [comment]
Hi @TALUPURI-DIMPLE-HIMA-BINDU, thanks for asking the question.

It's totally fine to use your app within a few channels at a time. Thus, that shouldn't be the reason why your app server does not receive some of the events.

The only possible cause apart from network/infra issues and/or Slack outage is ratelimits for Events API. Your app can receive only 30K events per hour. This means that if your app subscribes other events that can be delievered a lot (e.g., message events in a busy channel), app_mention event delivery can be affected by that. Please refer to the document for more details: https://api.slack.com/apis/rate-limits#events

If that's not your case, please contact our customer support team to check what's happening with your app and workspace. Since this is a public place, we're unable to ask you to provide any sensitive information like your workspace / channel metadata. If you're observing some unexpected behavior / errors, customer support agents can check server-side logs upon your approval. You can reach out to them via either /feedback in your Slack workspace or https://my.slack.com/help/requests/new . I hope this helps.

**Comment by TALUPURI-DIMPLE-HIMA-BINDU** [comment]
Thank you  @seratch for the reply we will contact support team .

**Comment by markomdinic** [comment]
Same here ...

**Comment by markomdinic** [comment]
they fixed it ... events are now pouring in
