### ISSUE TITLE
Slack Login with Enterprise org gives us `no_bot_scopes_requested` error

### ISSUE THREAD

**Issue by kennym** [slackapi/bolt-python#1157]
We have a distributed Slack App with `org_deploy_enabled=True`.

Our customer has successfully added it to their Enterprise Grid, we have a `SlackBot` and `SlackInstallation` record with both `is_enterprise_install=True`.

However, when we try the Slack Login, and select the org (not the workspace) from the dropdown selector, we get this page:

Logging in by selecting a workspace seems to work.

- Why do we need to provide bot scopes for Slack Login?
- Should we not be using the org for Slack Login, but a workspace instead?

### Reproducible in:

```bash
django-slack==5.19.0
slack_bolt==1.19.1
slack_sdk==3.31.0
ProductName:            macOS
ProductVersion:         14.6.1
BuildVersion:           23G93
Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
```

#### The `slack_bolt` version

slack_bolt==1.19.1

#### Python runtime version

Python 3.11.6
#### OS info

ProductName:            macOS
ProductVersion:         14.6.1
BuildVersion:           23G93
Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Visit the install path of our Slack App
2. Select the enterprise grid, not workspace, from the dropdown selector
3. Error page appears

### Expected result:

See the "Allow" screen, and allow us to continue

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @kennym, thanks for asking the question. 

Indeed, the error code is too cryptic to understand, but Sign in with Slack does not support org-level authorization. Instead, end-users have to pick a workspace under the org. Since your app supports org-wide installation, this difference may not make sense, but please inform the customer to log in with any workspace in the org. 

On your app's side, your app can perform user information retrieval API calls and identify who the user is in the org. As you may know, all users in an Enterprise Grid org are managed at the org level, so your app can safely assume the user ID is unique within the org and can match the user data within your app's database tables. 

I hope this clarifies things.

**Comment by kennym** [comment]
@seratch thanks for the explanation - this makes perfect sense.
