### ISSUE TITLE
Is there a way to access a user's list (NOT a list of users)

### ISSUE THREAD

**Issue by tracy-ash** [slackapi/bolt-python#1168]
I've searched but have not been able to determine if an app that I'm developing can access a list created by a user.
Is this possible using bolt?

**Comment by filmaj** [comment]
Hello! Unfortunately at this time, there are no List-related APIs for developers to consume 😢 

If this is a feature that you would like to see, I strongly recommend emailing feedback@slack.com and letting our excellent Customer Success team know that you are submitting a feature request for List APIs. Internally, our leadership prioritizes and takes seriously requests from customers of this nature, so that would be your best bet to see this kind of functionality become available.

Sorry for the trouble and I as well hope to see these APIs soon!
