### ISSUE TITLE
Updating message in threads for new Assistant view

### ISSUE THREAD

**Issue by kennym** [slackapi/bolt-python#1185]
I am not seeing updates being applied using [`chat.update`](https://api.slack.com/methods/chat.update) Web API method when using the Slack Assistant view.

#### The `slack_bolt` version

```
django-slack==5.19.0
slack_bolt==1.21.1
slack_sdk==3.33.1
```

#### Python runtime version

Python 3.11.6

#### OS info

```
ProductName:            macOS
ProductVersion:         15.0.1
BuildVersion:           24A348
Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000
```

#### Steps to reproduce:

1. Enable `assistant_view` for Slack App
2. Initialize Slack SDK client
3. Call `chat_update` method using either `slack_message["ts"]` or `slack_message["thread_ts"]` of the message returned from the Slack API.

```python
            client.chat_update(
                channel=channel, ts=slack_message["thread_ts"]
            )
```

### Expected result:

SPECTACULAR FAILURE... or updating of the message.

### Actual result:

Message is not being updated, no exception is raised, and Slack API returns a HTTP 200

**Comment by seratch** [comment]
Hi @kennym, thanks for asking the question. The channel_id and thread_ts are used for specifying an assistant thread, which means you cannot use thread_ts for updating a specific message within an assistant thread.

> slack_message["ts"]

The "ts" is usually usable for chat.update API calls, but I'm not sure how the "slack_message" data is received. If you could provide a bit more detail, such as the entire app.event listener (or assistant middleware code if you're using it), we might be able to help you debug your code or identify a potential bug on our SDK side.

**Comment by kennym** [comment]
> but I'm not sure how the "slack_message" data is received
Sorry, `slack_message` would be the JSON we get back from the `message.im` event via the Slack Events API, so the data about the Slack message.

I've tried using the `chat.update` Web API with the `ts` params which previously worked when not using the new Assistant feature for updating a message, but that stopped working. I've also tried using the `thread_ts` attribute for use with the `chat.update` API but that also doesn't work.

Do you have an example on how I could update a message when using the assistant feature?

**Comment by seratch** [comment]
I don't think we can share a simple example code for it. When your app receives a message event within app.event("message") / app.message event listener, the message should posted by a human user, rather than the app's bot user. If your app attempts to update the message using the bot token, it won’t succeed because the bot token lacks permission to update messages from other users. If your app have `ignoring_self_events_enabled: False` option when initializing it, your app can receive your app's bot user messages as well and chat.update should work work in such cases.

For building an assistant app, we highly recommend using Assistant middleware class to set up your listeners: https://tools.slack.dev/bolt-python/concepts/assistant The middleware does many things for you. If you have a certain reason to continue implementing app.event / app.message for assistant threads, reviewing these listener codes may be beneficial: https://github.com/slack-samples/bolt-python-assistant-template/tree/main/listeners/events

Lastly, I understand you may not be able to share your actual code, but if you could provide some simplified code that reproduces the issue, we'd be happy to assist you further.

**Comment by kennym** [comment]
![image](https://github.com/user-attachments/assets/fea8b9cc-1462-4357-bd95-2c51219ab3e8)
![image](https://github.com/user-attachments/assets/5a6c946c-5599-4630-963e-40768c7a8c8a)

**Comment by kennym** [comment]
This is an example of an error ☝️

**Comment by kennym** [comment]
ok, here I get with a valid `ts`:

![image](https://github.com/user-attachments/assets/80418dea-fb49-4f17-a4e5-45ea793d607b)

**Comment by kennym** [comment]
this only happens with the assistant view feature enabled.

**Comment by kennym** [comment]
ok, I found the problem.

We were using the `conversations.history` for fetching messages in a channel, but with the assistant view enabled that didn't return the messages we neeed.

I switched to `conversations.replies` and that fixed our problem immediately.

**Comment by kennym** [comment]
ok, I found the problem.

We were using the conversations.history for fetching messages in a channel, but with the assistant view enabled that didn't return the messages we neeed.

I switched to conversations.replies, providing the ts with the valued of the thread and that got us back the correct messages we could update.
