### ISSUE TITLE
Saving OAuth2.0 generated token to external db, to prevent invalidation of app install

### ISSUE THREAD

**Issue by amogh-jrules** [slackapi/bolt-python#214]
I have written Slack Bolt bot in Python which I intend to distribute on the App Directory. This requires me to enable OAuth2.0 in my app, which I have done following the instructions in the [docs](https://slack.dev/bolt-python/concepts#authenticating-oauth).
I have hosted my app on heroku, and everytime I push a new release, the existing installation in my slack team gets invalidated. 
I understand that this happens because the token is saved on the ./data directory (as in the documentation) and does not persist.

The docs mention that I have to modify the OAuthStateStore [github](https://github.com/slackapi/python-slack-sdk/blob/919febeaf660d001f0c81c961fb1ed29255a0162/slack_sdk/oauth/state_store/state_store.py#L4), but that doesnt seem to do much.
I was wondering if there was an straightforward way to this, like Bolt for JS has for the same functionality 
![image](https://user-images.githubusercontent.com/31567169/104938654-ccd87080-59c8-11eb-91a5-931285b04eb8.png)

Any help or guidance is much appreciated!

**Comment by mwbrooks** [comment]
Hey @amogh-jrules, thanks for reaching out! It sounds like you understand why this is happening - Heroku doesn't persist the filesystem between deploys, so the `./data` directory is removed on each re-deploy.

The FileSystem/SQLite database is great for development, but not ideal for production since it only persists in memory and on the filesystem. [Heroku has a decent (but dated) article explaining this is more detail.](https://devcenter.heroku.com/articles/sqlite3)

For Python, I think you'll want to use the `SQLAlchemyInstallationStore` adapter, which uses [SQLAlchemy](https://www.sqlalchemy.org/). You can [follow this example code](https://github.com/slackapi/bolt-python/blob/2216935b522dfc7f511e45252b76ffff5832ecb3/examples/sqlalchemy/oauth_app.py) to connect Bolt to a PostgreSQL database. And you can [spin up a PostgreSQL database with Heroku](https://www.heroku.com/postgres).

Hope that helps and, please, let me know how it goes!

**Comment by amogh-jrules** [comment]
@mwbrooks Thanks for the prompt response! Yeah that looks promising, I spent a lot of time trying to rewriting the Slack SDK OAuth classes inorder to find something that works.
I'll give this a spin and let you know how it came along, appreciate the effort 🙌🏽

**Comment by mwbrooks** [comment]
@amogh-jrules aweeeeeesome! 🎉 Sorry to hear that you spent so much time rewriting the OAuth methods, but it's great to hear that you're good to go now 🙂
