### ISSUE TITLE
How to implement workflow steps in aws lambda?

### ISSUE THREAD

**Issue by pedubueno** [slackapi/bolt-python#237]
I saw saw some examples of how to implement workflow steps but none of them is how to do that in a FaaS env (lambda). All the examples regarding FaaS are related to commands, where you need to implement a listener for the ack and one for the lazy function(s):

```
app.command("/start-process")(
    ack=respond_to_slack_within_3_seconds,  # responsible for calling `ack()`
    lazy=[run_long_process]  # unable to call `ack()` / can have multiple functions
)
```
How I do something like that when creating a WorkflowStep instance? 

#### The `slack_bolt` version

slack-bolt==1.3.1
slack-sdk==3.3.1

#### Python runtime version

Python 3.8.7

#### OS info

ProductName:    Mac OS X
ProductVersion: 10.15.5
BuildVersion:   19F96

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @pedubueno, [this example](https://github.com/slackapi/bolt-python/blob/v1.3.1/examples/workflow_steps/steps_from_apps_decorator.py) should be helpful to you. To run the app on AWS Lambda, you can use the adapter [this way](https://github.com/slackapi/bolt-python/blob/v1.3.1/examples/aws_lambda/aws_lambda.py#L28-L34) instead of using `app.start()` method.

**Comment by seratch** [comment]
As I've provided an answer to this question, let me close this issue. Please feel free to write in if you have anything further to ask.
