### ISSUE TITLE
Updating a modal with a title > 24 chars silently fails (at least in socket mode)

### ISSUE THREAD

**Issue by brettp** [slackapi/bolt-python#241]
### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.3.2
slack-sdk==3.3.2

#### Python runtime version

Python 3.9.0

#### OS info

ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524
Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64

#### Steps to reproduce:

1. Register a handler that updates a modal view with `ack(response_action="update")`
2. Set the title > 24 chars

### Expected result:

The server / SDK should complain the title is > 25 chars, like it does when trying to create a modal.

### Actual result:

The view fails to update, with a message on the Slack client "We had some trouble connecting. Try again?" No errors are indicated from the SDK itself or logs. Execution continues in the handler.

```

@app.view('handle_submit')
def handle_submit(ack, body, client, view):
    ack(
        response_action="update",
        view={
            "type": "modal",
            "title": {
                "type": "plain_text",
                "text": "This text is way too long for the title"
            },
            "blocks": [
                {
                    "type": "section",
                    "text": {
                            "type": "plain_text",
                            "text": "Test"
                    }
                }
            ]
        }
    )

    print("Should throw before getting here...")
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hey @brettp, thanks for taking the time to submit this issue! 

As a first time, I think one of us will want to re-create the issue with HTTP Mode to confirm whether this is an error specific to Socket Mode. After that, we can look into how to improve the error message.

**Comment by mwbrooks** [comment]
Hey @brettp, I should have noticed that you were responding to a `response_action="update"` request. At first, I thought the example was making a request to open a view.

Since you're responding to a request, the Slack API is unable to respond back with validation errors. This is a limitation of `ack` and the Bolt framework doesn't perform Block Kit validations since it's the Slack API typically does. This is why no error is thrown by the `ack` method.

If you were opening a view, where you make a request to the Slack API, then the API would respond with a validation error similar to:

```json
{
    "code": "slack_webapi_platform_error",
    "data": {
        "ok": false,
        "error": "invalid_arguments",
        "response_metadata": {
            "messages": [
                "[ERROR] must be less than 25 characters [json-pointer:/view/title/text]"
             ]
        }
    }
}
```

However, since updating a view is performed as a response (rather than request) there's no opportunity for the Slack API to return a validation error.

**Comment by brettp** [comment]
@mwbrooks - Thanks for the quick reply! Apologies for not making it clearer that it was a snip of code and not a full interaction.

What you say definitely makes sense and is obvious when you think about it. In this case, raising an exception on the SDK side might be sufficient to let the dev have a bit more context on the client-side error.

**Comment by mwbrooks** [comment]
Hey @brettp, no worries. Modals are confusing because some are opened with requests while others are updated with responses. A request allows the server to respond with a validation error, but a response doesn't. 🤔

It would be nice to throw a client-side error, but we've experienced some issues in the past when doing this.

We've learned to avoid adding server-side validation to the client because the validation rules can change without notice and become outdated. In the past, we've had validation logic such as the [Python SDKs Block Kit](https://github.com/slackapi/python-slack-sdk/blob/v3.4.0/slack_sdk/models/blocks/blocks.py#L31) trigger incorrectly because the Slack API updated their validation rules (changing the max length, adding new required params, etc).

Even if we update the SDK, developers using older version of the SDK may start to experience unexpected results because the client and server would enforce different rules.

We could reliably implement client-side validation if the Slack API implemented granular versions. This would allow the client to "lock" itself to a specific version of the Slack API. Unfortunately, that's not the case right now.

I hope that helps explain why we're unable to add a client-side error check. Although it would be nice to have!
