### ISSUE TITLE
API does not allow a single input checkbox to be deselected

### ISSUE THREAD

**Issue by robmsmt** [slackapi/bolt-python#295]
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:

```
slack-bolt==1.4.4
slack-sdk==3.4.2
Ubuntu 20.04
```

#### Python runtime version

Python 3.8.5

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

```
{
                "type": "input",
                "block_id": "uf_check_b4",
                "element": {
                    "type": "checkboxes",
                    "initial_options": [
                        {
                            "value": "value-0",
                            "text": {
                                "type": "plain_text",
                                "text": "Cancel existing - This will cancel any pending releases"
                            }
                        }
                    ],
                    "options": [
                        {
                            "text": {
                                "type": "plain_text",
                                "text": "Cancel existing - This will cancel any pending releases",
                                "emoji": True
                            },
                            "value": "value-0"
                        }
                    ],
                    "action_id": "checkboxes-action"
                },
                "label": {
                    "type": "plain_text",
                    "text": "Additional options",
                    "emoji": True
                }
            }
```

### Expected result:
This checkbox is checked by default. It should be allowed to be unchecked - it appears there's a minimum required number of checkpoints (at least one checkbox needs to be checked?). Can this be changed? No reference to this requirement in the [docs](https://api.slack.com/reference/block-kit/block-elements#checkboxes)

### Actual result:

It cannot be unchecked. If it is it fails modal input validation.
![Screenshot from 2021-04-13 15-38-12](https://user-images.githubusercontent.com/16005758/114571385-8a909980-9c6e-11eb-9b4f-485f5fc4066e.png)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hey @robmsmt 👋🏻 

Thanks for the detailed message. I agree that it appears to be a Slack API Platform issue because a **single unchecked checkbox should be allowed** and should not return a required field error.

**I'm going to pass this issue to our server-side team.** If I hear any feedback or guidance, I'll add it back to this issue. Unfortunately, we can't guarantee when this issue will be fixed - it'll enter Slack's internal engineering backlog. Typically, you can follow the [API Changelog](https://api.slack.com/changelog) to learn about improvements and fixes. However, if I notice the fix land, I'll try to update this issue for you!
