### ISSUE TITLE
Way to receive newly sent message in channel on Socket Mode.

### ISSUE THREAD

**Issue by jeyraof** [slackapi/bolt-python#296]
Is there any way to get newly sent message by other user for not only including mention but also every messages?

In my app, below scopes was set. 
<img width="204" alt="image" src="https://user-images.githubusercontent.com/2032880/114911108-a1471400-9e59-11eb-97ef-38ef36362922.png">

But only app_mention type event was received.

**Comment by stevengill** [comment]
Hey @jeyraof,

You want to subscribe to some message events. See https://api.slack.com/events/message

**Comment by jeyraof** [comment]
@stevengill Thank you for your attention. For clearly understanding, Is "subscribe" you mentioned RTM not Event API?

**Comment by stevengill** [comment]
not RTM. If you go to your app config page (API.slack.com/apps) and go to your app and click "Event subscriptions" in the left hand menu, you can subscribe to bot events.

**Comment by mwbrooks** [comment]
@jeyraof If possible you should use the Events API because the RTM API has been deprecated (it's only available to classic Slack apps).

If you want to receive all messages from other users, you may need the following scopes:

* [message.channels](https://api.slack.com/events/message.channels) listens for messages in public channels that your app is added to
* [message.groups](https://api.slack.com/events/message.groups) listens for messages in private channels that your app is added to
* [message.im](https://api.slack.com/events/message.im) listens for messages in your app’s DMs with users
* [message.mpim](https://api.slack.com/events/message.mpim) listens for messages in multi-person DMs that your app is added to

From your screenshot, it doesn't look like you're currently using any of those channels. So I hope that helps you out!

**Comment by jeyraof** [comment]
Oh, I got it. Thank you a lot @mwbrooks @stevengill ! 🙏
