### ISSUE TITLE
Unhandled Request using Socket Mode

### ISSUE THREAD

**Issue by mariebarrramsey** [slackapi/bolt-python#301]
I'm using the python slack_bolt socket mode for my slack app following the instructions here: https://github.com/slackapi/bolt-python but no matter what get an unhandled request error. My app is in socket mode. I just want to write a simple slash command over socket mode. I've scoured the documentation and can't find any steps I'm missing but I'm new to using socket mode/ slack_bolt so could be missing a crucial step here. Any help appreciated!

#### The `slack_bolt` version

slack-sdk==3.5.0
slack-bolt==1.5.0

#### Python runtime version

python==2.7.16

#### OS info

ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524
Darwin Kernel Version 19.6.0

#### Steps to reproduce:

1. app = App(token = "xxxxx")
2. handler = SocketModeHandler(app, "xxxx")
3. handler.start()
4. Add the following code

```python
@app.command("/hello")
def hello_command(ack, body):
    user_id = body["user_id"]
    ack(f"Hi, <@{user_id}>!")
```

### Expected result:

Slack will return Hi, "user" when someone runs the /hello slash command from slack. 

### Actual result:

"Unhandled request" with (`{'token': 'xxx', 'team_id': 'xxx', 'team_domain': 'xxx', 'channel_id': ....` etc)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @mariebarrramsey, thanks for asking the question!

As you shared at https://github.com/slackapi/bolt-python/issues/197#issuecomment-825222499, more detailed payload looks like: ` ({'token': 'xxx', 'team_id': 'xxx', 'api_app_id': 'xxx', 'event': {'type': 'message', 'subtype': 'bot_message', 'text': ...`, right? If so, this is [a message event](https://api.slack.com/events/message/bot_message) sent by your Events API data subscription. Your slash command posts a new message. That's why the message event was sent right after the slash command invocation.

If you don't use the message events at all, you can remove it from the subscriptions in **Event Subscriptions** under https://api.slack.com/apps . If you would like to handle it properly, you can add `app.message` or `app.event("message")` listeners to your app. Refer to https://slack.dev/bolt-python/concepts#message-listening for more details.

If everything is clear, may I ask you to close this issue?

**Comment by mariebarrramsey** [comment]
Sorry, I think I had just copied the other user's payload from before (my payload is the one on this ticket). I don't think I'm using a message event. I only want to use the slash command. This is my exact payload: 
Unhandled request ({'token': ‘xxx’, 'team_id': ‘xxx’, 'team_domain': ‘xxx’, 'channel_id': 'xxx', 'channel_name': 'xxx', 'user_id': 'xxx', 'user_name': 'xxx', 'command': ‘/hello’, 'text': 'test', 'api_app_id': 'xxx', 'is_enterprise_install': 'false', 'enterprise_id': 'xxx', 'enterprise_name': 'xxx', 'response_url': 'xxx', 'trigger_id': 'xxx'})

**Comment by seratch** [comment]
@mariebarrramsey I recommend enabling debug level logs: https://slack.dev/bolt-python/concepts#logging

Then, if you don't see the following output in stdout:

```
DEBUG:slack_bolt.App:Checking listener: hello_command ..
```

the listener is not registered to your `App` instance yet. A common pattern that may result in this situation is that a developer places listeners after the `handler.start()` call. You need to place the method call at the bottom of your source code.

**Comment by mariebarrramsey** [comment]
I think the problem was that I made up the arguments to my function (ack, body). Using the functions from the site you linked and the debugger I got it to work! Thank you!
