### ISSUE TITLE
Potentially request.body can be None when using a custom adapter

### ISSUE THREAD

**Issue by matteobaldelli** [slackapi/bolt-python#330]
I think you should swap the order of this line, with  aws_lambda `body` is `None` so the code will raise the exception inside the if condition. L49 not make any sense in this order because if `body` is `None` the code will always raise exception inside the if condition

https://github.com/slackapi/bolt-python/blob/31436f729871c38f596a1363aa1d61a5b4c15d0d/slack_bolt/request/request.py#L47-L49

**Comment by seratch** [comment]
Hi @matteobaldelli, thanks for taking the time to report this issue!

As long as you use [the adapter in this project](https://github.com/slackapi/bolt-python/blob/v1.6.0/slack_bolt/adapter/aws_lambda/handler.py#L78), the `body` cannot be `None`. However, if a developer implements their own adapter, the `body` is possibly `None` in some cases.

I will update the code (perhaps, rather than swapping the lines, I will update the L47 to check if it's not None).
