### ISSUE TITLE
Getting operation timeout after immediate ack() call

### ISSUE THREAD

**Issue by tomeszmh** [slackapi/bolt-python#335]
Hey! 
In the api doc you says that i should return immediately wiht ack() method call to avoid operation timeout message.
I have an AWS lambda function with SlackRequestHandler, and I immediately call ack() after i receive a slash command, but i always get operation timeout message. 
After ack() i have some business logic implementation. (Db reads and so on...)
Thank you

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version
slack-bolt==1.5.0
slack-sdk==3.5.0

#### Python runtime version

3.8.5
(Paste the output of `python --version`)

#### OS info
Darwin Kernel Version 20.4.0: 

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

```
@app.command("/help")
def handle_help_command(
        ack: Ack, client: WebClient, body: dict, respond: Respond, logger: Logger
) -> None:
    ack()
```
3 business logic goes here....
### Expected result:

Theres no any error message due to timeouts...

### Actual result:
operation timeout

(Tell what actually happened with logs, screenshots)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hi @tomeszmh,

You're right that our recommendation is to always `ack()` a request as-soon-as possible. This is because the Slack API requires the request to be acknowledged in less than 3 seconds, otherwise it will timeout and possibly retry the request (resulting in multiple responses to sent to Slack sometimes).

AWS Lambda and Slack API have some conflicting requirements because AWS Lambda will terminate the function after a response is returned. This means the moment `ack()` is called, the AWS Lambda function may terminate. The two aren't an ideal combination!

To work around this, we have an [AWS Lambda adapter](https://github.com/slackapi/bolt-python/tree/main/slack_bolt/adapter/aws_lambda) and an [example of using the AWS Lambda Adapter](https://github.com/slackapi/bolt-python/tree/main/examples/aws_lambda) (this is the [most interesting file](https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/lazy_aws_lambda.py)). The idea is that you can use "lazy listener" to immediately respond to a Slack API request (such as a slash command) and then trigger a new AWS Lambda function to handle some long running task (like a database query). You can also learn more about the API design in issue https://github.com/slackapi/bolt-python/issues/34.

Let me know how that goes!
Michael

**Comment by tomeszmh** [comment]
It's working like you mentioned, i tried. Thank you so much for the detailed explanation! 
;)
