### ISSUE TITLE
Is `Ack()` returning a no-op function?

### ISSUE THREAD

**Issue by offbyone** [slackapi/bolt-python#381]
I'm writing a Slack bot that is running in AWS Lambda. I have several functions that take a couple of seconds to complete, so I'm making sure to `ack()` them ASAP:

```python
@app.event("/slashcmd")
def slash_cmd(ack, client, context, respond):
    ack()
    # do something that takes a while
    bot_info = client.users_info(user=context["bot_user_id"]).validate()
    respond("some results")
```

What I'm observing on the Slack end is when I invoke `/slashcmd` I end up getting the results of the command, followed by a timeout notice from Slack itself, and I think I have figured out why. In /slack_bolt/context/ack/ack.py there does not appear to be _any_ call to the Slack API client in order to send back the ack. The code there just sets a `BoltResponse` that it constructs, without any remote activity at all. You can see the full code [here](https://github.com/slackapi/bolt-python/blob/0927de45b265bc4d16570ceb6a23cb5dd0a21317/slack_bolt/context/ack/internals.py#L12) at the current revision.

I can confirm that, regardless of log levels, I never see any Slack API calls being sent for my `ack()` calls.

I am truly hoping I'm missing something obvious here. :)

Here is a (redacted, but representative) log of the events in my Slack event handler. Every instance of an outbound API call is present here (marked by the `Sending a request - ` prefix, which comes from one of the clients in your SDK, not sure which):

```
START RequestId: c0fe9f9c-dcfe-4dd3-8f6f-c5288b3991cd Version: 79
2021-06-15 23:36:50,227 Incoming event: {'resource': '/slack/events', 'path': '/slack/events', *REDACTED* }
2021-06-15 23:36:50,228 Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
2021-06-15 23:36:50,228 Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
2021-06-15 23:36:50,228 Applying slack_bolt.middleware.authorization.single_team_authorization.SingleTeamAuthorization
2021-06-15 23:36:50,228 Applying slack_bolt.middleware.ignoring_self_events.ignoring_self_events.IgnoringSelfEvents
2021-06-15 23:36:50,228 Applying slack_bolt.middleware.url_verification.url_verification.UrlVerification
2021-06-15 23:36:50,228 Checking listener: *REDACTED* ...
2021-06-15 23:36:50,228 Running listener: *REDACTED* ...
2021-06-15 23:36:50,228 Sending a request - url: https://www.slack.com/api/users.info, query_params: {}, body_params: {'user': '*REDACTED*'}, files: {}, json_body: None, headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': '(redacted)', 'User-Agent': 'Bolt/1.6.1 Python/3.8.10 slackclient/3.6.0 Linux/4.14.231-180.360.amzn2.x86_64'}
2021-06-15 23:36:50,455 {"bot_info": {*REDACTED*}}
2021-06-15 23:36:50,968 Sending a request - url: https://www.slack.com/api/chat.postMessage, query_params: {}, body_params: {}, files: {}, json_body: ...}
2021-06-15 23:36:51,640 Responding with status: 200 body: "" (1411 millis)
END RequestId: c0fe9f9c-dcfe-4dd3-8f6f-c5288b3991cd
```

Note that there is no "sending a request" for an ack.

#### The `slack_bolt` version

Bolt 1.6.1

#### Python runtime version

Python 3.8 (from AWS Lambda)

#### OS info

No idea which OS :)

#### Steps to reproduce:

call `ack()` from my bolt event handler.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @offbyone, as you found, `ack()` method call does not perform any Web API call. The responsibility of the method is to set the content to return as an HTTP response (or WebSocket message in Socket Mode). 

The internal code around this may need more time to understand than you expect. So, let me try to explain what Bolt does for you regarding this. I hope the following is good enough for helping you understand it. All the things that Bolt's `ack()` mechanism does are:

* ListenerRunner (default one is threads-based) [starts an async execution of a listener function](https://github.com/slackapi/bolt-python/blob/v1.6.1/slack_bolt/app/app.py#L506-L514). 
* Inside the runner, [the main thread runs your listener function asynchronously (in a different thread)](https://github.com/slackapi/bolt-python/blob/v1.6.1/slack_bolt/listener/thread_runner.py#L108-L140)
* While running the listener in another thread, the main thread [waits for the `ack()` call, which tells the response to send](https://github.com/slackapi/bolt-python/blob/v1.6.1/slack_bolt/listener/thread_runner.py#L156-L15)
* Once the response is set, the main thread immediately returns the data as the acknowledgement to the Slack server

With this way, your Bolt app can send an HTTP response right after the `ack()` method call while the rest in your listener function are still running in threads. As you are already aware, this is for easily avoiding 3 second timeouts.

When it comes to AWS Lambda or any FaaS runtime, the things are not so simple. The above approach does not work as the FaaS runtime can be terminated at any time once the lambda function returns. Therefore, we introduced `process_before_response` option. If the flag is true, the Bolt framework holds off sending an HTTP response until all the things in a listener function are done. With this, 3 second timeouts may arise if the listener takes a few seconds.

As a better solution for this, we've added lazy listener function mechanism in Bolt for Python. Here is the document about the feature: https://slack.dev/bolt-python/concepts#lazy-listeners 

As you can see in the document, interestingly this feature uses AWS Lambda functions instead of threads. As long as your lambda function has the permission to invoke the function itself, Bolt framework does all the things under the hood.

I hope this was helpful to you.

**Comment by offbyone** [comment]
That's helpful, yes, although I'm a bit confused, now; this seems to imply that even if I acknowledge an event, my entire handler invocation needs to be complete within 3 seconds. Is that the case? Am I not able to take longer under any circumstances, even if I've acknowledged the call?

**Comment by offbyone** [comment]
Looking at this example a bit further, it looks like any checks you do in the `ack` function need to be repeated in the lazy handler, since no matter what we do in `ack` the lazy functions will still be invoked. Is there a way to prevent the lazy calls from happening if the ack function determines that there was an error?

**Comment by offbyone** [comment]
(FYI, limitations notwithstanding -- it would be super helpful to have a `nack` option in there :) -- this solves my problem nicely. When can I expect the API to leave beta and be stabilized? I'm content to run this way and watch out for changes, but I'd like to have a sense of when they'll go final)

**Comment by seratch** [comment]
>this seems to imply that even if I acknowledge an event, my entire handler invocation needs to be complete within 3 seconds. Is that the case? Am I not able to take longer under any circumstances, even if I've acknowledged the call?

* The default setting: **No**. You can do whatever time-consuming after the `ack()` method call. As I mentioned above, if you run with this setting, the code after `ack()` can be killed by the FaaS runtime.
* `process_before_repsonse=True` on FaaS: **Yes**
* ack / lazy listener functions: **Yes** for `ack` / **No** for `lazy` ones

> it looks like any checks you do in the ack function need to be repeated in the lazy handler, since no matter what we do in ack the lazy functions will still be invoked. Is there a way to prevent the lazy calls from happening if the ack function determines that there was an error?

Good point. There is no way to do this at the moment but introducing a new option like `invoke_lazy_if_acked=True` (default: False) would be a great addition. Is this what you mean?

>When can I expect the API to leave beta and be stabilized? I'm content to run this way and watch out for changes, but I'd like to have a sense of when they'll go final

We won't change the APIs but the only reason why we mark it as beta is that we may not support it in other Bolt frameworks (Node.js, Java).

**Comment by seratch** [comment]
Let me know if you have more to ask/discuss here. I will close this issue after waiting for your response for a few more days.

**Comment by seratch** [comment]
Let us close this issue but please feel free to write in whenever you have more to discuss on this topic 👋
