### ISSUE TITLE
Is it possible to customize our slack bolt block kit styling specially buttons?

### ISSUE THREAD

**Issue by umairnsr87** [slackapi/bolt-python#395]
**Explanation**:Do we have anything to customize our bolt block kit, adding styles when a button is pressed or few buttons are pressed and then we can process the input of all the form at the same time. 

**Explanation**: I have a form of few elements lets say 3 buttons, 2 radio buttons initially what happens is when a person choose anything then I have to handle all the actions independently so for 5 elements I have to handle 5 actions. The better and more feasible option is let the user select everything and then I can handle only one action and all of them(elements) can be fetched from the same form. Is it possible or I have no other choice.

**Comment by mwbrooks** [comment]
Hi @umairnsr87 👋🏻 

> Explanation:Do we have anything to customize our bolt block kit, adding styles when a button is pressed or few buttons are pressed and then we can process the input of all the form at the same time.

There is limited button styling available. You can [customize between 3 buttons colors](https://api.slack.com/reference/block-kit/block-elements#button) but you cannot customize the "state" (the color while pressed or hovered).

> Explanation: I have a form of few elements lets say 3 buttons, 2 radio buttons initially what happens is when a person choose anything then I have to handle all the actions independently so for 5 elements I have to handle 5 actions. The better and more feasible option is let the user select everything and then I can handle only one action and all of them(elements) can be fetched from the same form. Is it possible or I have no other choice.

I can understand your desire to allow the user to select everything and then handle only one action. It's a smoother experience for the user and less code for you. You'd accomplish this by [opening a modal view](https://slack.dev/bolt-python/concepts#opening-modals) and [listening for the submission](https://slack.dev/bolt-python/concepts#view_submissions). On the submission, you can return errors for specific fields. 

Thinking aloud, you may want to switch the 3 buttons to be something else, such as [checkboxes](https://api.slack.com/reference/block-kit/block-elements#checkboxes) or a [multi-select menu](https://api.slack.com/reference/block-kit/block-elements#multi_select). The reason is that a button must listen to an action (press).

**Comment by umairnsr87** [comment]
Thanks alot @mwbrooks
