### ISSUE TITLE
Question: Can Bolt app/socketmode be set to listen only on specific channel?

### ISSUE THREAD

**Issue by jcastro-sfdc** [slackapi/bolt-python#399]
I'd like to clean up all the other chatter I see from other channels the app is not installed in.  Below is an example

```
WARNING:slack_bolt.App:Unhandled request ({'type': 'event_callback', 'event': {'type': 'member_joined_channel'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("member_joined_channel")
def handle_member_joined_channel_events(body, logger):
    logger.info(body)

INFO:slack_bolt.App:Unsuccessful Bolt execution result (status: 404, body: {"error": "unhandled request"})
DEBUG:slack_bolt.App:Message processing completed (type: events_api, envelope_id: e2761daf-72a4-4801-8c14-7d157c50a1b8)
```

**Comment by seratch** [comment]
Hi @jcastro-sfdc, thanks for asking the question!

>Can Bolt app/socketmode be set to listen only on specific channel?

For the bot events in Event Subscriptions (Events API), your app subscribes to only the events that occur in the channels your app's bot user is a member of. If your app does not need to monitor a specific channel, you can remove the app from the channel. Apart from doing so, there is no way to filter out channel-related events while your app's bot user is in a channel.

I hope this was helpful to you.

**Comment by eddyg** [comment]
@jcastro-sfdc FWIW, since your bot is subscribed to `message` events, you can also use a generic handler to transparently process any unneeded subtypes for the channels your bot is in, as shown [in this example](https://github.com/slackapi/bolt-python/blob/v1.6.1/examples/message_events.py#L78-L82).

There are also [app_mention](https://api.slack.com/events/app_mention) events, which generate less “chatter” and may work for you, depending on your use case.

**Comment by jcastro-sfdc** [comment]
@eddyg @seratch Thank you very much!
