### ISSUE TITLE
Replying with 0 results for a multi-select external option display previous successful results

### ISSUE THREAD

**Issue by prziborowski** [slackapi/bolt-python#468]
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.9.1
slack-sdk==3.10.1

#### Python runtime version

Python 3.8.10

#### OS info

#36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Create a socket mode app with shortcut (e.g. test-open for below source)
2. Run the app below and trigger the shortcut
3. Type in for the multi-select. It will generate 1, then 2 options and then 0 options. 

```python
#!/usr/bin/env python3
import json
import os
import tempfile
import time

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

bot_token = os.environ['BOT_TOKEN']
app = App(token=bot_token)
count = 0


@app.shortcut('test-open')
def test_open(ack, shortcut, client):
    client.views_open(
        trigger_id=shortcut['trigger_id'],
        view={
            'type': 'modal',
            'callback_id': 'view-response',
            'title': {'type': 'plain_text', 'text': 'Test update'},
            'close': {'type': 'plain_text', 'text': 'Close'},
            'submit': {'type': 'plain_text', 'text': 'Send'},
            'blocks': [
                {
                    'type': 'section',
                    'block_id': 'test-section',
                    'text': {
                        'type': 'plain_text',
                        'text': 'Enter something'
                    },
                    'accessory': {
                        'action_id': 'action',
                        'type': 'multi_external_select',
                        'placeholder': {
                            'type': 'plain_text',
                            'text': 'Type something'
                        },
                        'min_query_length': 1
                    }
                }
            ],
        }
    )


@app.options('action')
def handle_options(ack, body):
    global count
    count = (count + 1) % 3  # Returns 0 results every 3 times.
    opts = []
    for i in range(count):
        opts.append({
            'text': {
                'type': 'plain_text',
                'text': f'Sample {i}'
            },
            'value': f'sample-{i}'
        })
    if len(opts) == 0:
        print('Sending 0 options')
    ack(options=opts)


if __name__ == '__main__':
    handler = SocketModeHandler(app, os.environ["APP_TOKEN"])
    handler.start()
```

### Expected result:

When the multi-select option display 0 results I expect it to return "Nothing could be found."

### Actual result:

The options listed are based on the previous successful results.
This behavior confuses users as the results don't match what they were searching.
I'm not sure if this is a bolt-python issue, or something else (I never got to doing something this advanced when I had to write the websocket or REST code)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by srajiang** [comment]
Hey @prziborowski - That's interesting. Based on what your code is doing here in sending an empty `opts` array every 3 times, this seems related to the default behavior of the `multi_external_select`, not bolt-js. It appears to be caching previously results as you point out. If you return an empty opts the first time, we do receive the "Nothing could be found" message, but only then.

I agree, that's confusing. I'm not sure that there is a workaround for this at the moment to get the behavior you want, since this is outside of bolt-js, but I will take this feedback to the team internally. 🙇

**Comment by prziborowski** [comment]
Did the team come back with any reply on whether this is intended behavior or not?

For now I've worked around it by returning a result that states "Please try a broader query." and hope no one clicks on that.

**Comment by srajiang** [comment]
@prziborowski - Thank you for looping back on this. I submitted this behavior as feedback and it's looking like it's a bug. I'm going to signal boost with our technical architecture team to see if we can confirm.

Thanks for sharing your workaround - that will be helpful for anyone looking around whose noticed the same issue. 

Also, FYI the maintainers are trying out a new flow with github-actions to see whether we can get more threads / issues to resolution by surfacing them proactively. Since we're commenting again on this thread, it's no longer considered stale!

**Comment by prziborowski** [comment]
I guess the bot doesn't like the lack of updates.
Did the technical architecture team come back with a response on whether it will be considered a bug?

Thank you.

**Comment by seratch** [comment]
Hi @prziborowski, we've checked this issue again and found that this is a bolt-python bug. We'll fix this quickly and release a new patch versions shortly. We're so sorry for keeping you waiting here for a while.
