### ISSUE TITLE
chat_postMessage method is sending duplicate messages

### ISSUE THREAD

**Issue by RachelDong** [slackapi/bolt-python#469]
Hello,

I'm using the slack API to send notification to users. I used the Python apscheduler package to send the message, say once a week. But the message I received every time is duplicated, like:
![图片](https://user-images.githubusercontent.com/34002808/133976142-93b04b79-81d1-4d5e-aecc-7afff1c21c29.png)

I'm not sure why I got two same messages when I use the chat_postMessage method once.
My code is like:
```
def notification():
    slack_bot_client = WebClient(token=****)
    slack_bot_client.chat_postMessage(channel=***,text='notice you')

if __name__ == '__main__':
    scheduler = BackgroundScheduler(timezone='Asia/Shanghai')
    scheduler.add_job(remind_await,'cron',day_of_week=0,hour=15,minute=25)
    scheduler.start()
    ### use socket mode to run the app to listen and respond to other user requests
    SocketModeHandler(bot_app,app_token).start()
```

**Comment by filmaj** [comment]
Hello @RachelDong,

Can you share more of your application code? What you shared is insufficient to understand the full functioning of your app, in particular, the `remind_await` function/module, and any other code that connects `remind_await` to the `notification()` method.

**Comment by seratch** [comment]
Hi @RachelDong, the most likely cause would be that two running processes are running for some reason. Can you try the following and see how it goes?

* Create a new app-level token with [connections:write](https://api.slack.com/scopes/connections:write) scope
* Start a new app using the token
* Terminate all the existing processes you are aware of
* Disable the existing app-level tokens

After doing this, I am guessing that the issue should no longer arise.

As a preventive measure for this kind of situation, I would recommend a more robust approach such as having an external scheduler rather than as the code within each application instance. For example, if your app exposes an internal web endpoint to post a message in Slack and you have a stable scheduler somewhere else (ideally, managed service), managing the activities of the triggers and handler invocations would be much easier.

I hope this helps!

**Comment by RachelDong** [comment]
Hi @seratch ! Thank you for the advice! That helps me resolve the problem!
