### ISSUE TITLE
How do I create multiple socket connections with Bolt framework?

### ISSUE THREAD

**Issue by sharvesh06** [slackapi/bolt-python#515]
My app fails at times when the socket connection is unavailable, How do I create multiple socket connections with python Bolt framework?

**Comment by srajiang** [comment]
Hi @sharvesh06 - have you taken a look at #448 yet? Is that helpful to you?

**Comment by sharvesh06** [comment]
I did, do you have an example on how to do that with the bolt framework? #448 doesn't have an example

**Comment by seratch** [comment]
@sharvesh06 
If you mean that establishing multiple connections from a single Python app process, you can instantiate multiple `App` instances and call `SocketModeHandler#connect()` method for each instead of `#start()` method, which blocks the current thread: https://github.com/slackapi/bolt-python/blob/v1.10.0/slack_bolt/adapter/socket_mode/base_handler.py#L29

But, in general, I would recommend running multiple apps in scale-out approach, which means that you can deploy your app to up to 10 (this is the upper limit to connect to the Socket Mode server-side) hosts or containers. With this way, your each app just call `#start()` method. This makes your app code much simpler and easier to operate.

I hope this was helpful!

**Comment by seratch** [comment]
@sharvesh06 Let us know if you need more help here 👋 If we don't hear back for a few more days, we'll close this issue due to inactivity.
