### ISSUE TITLE
not_allowed_token_type when calling client.search_messages

### ISSUE THREAD

**Issue by joshight** [slackapi/bolt-python#539]
(Describe your issue and goal here)

Trying to implement a feature where the app(bot) does a historical search in a channel for a given search string. 

This api call requires a user token and I'm not sure how to implement it with Bolt. 

Any examples or advice on how to do this since the app is being instantiated with only a bot token and  signing secret:

```
APP = App(
    token=SLACK_BOT_TOKEN,
    signing_secret=SLACK_SIGNING_SECRET,
    process_before_response=True)



```
Thanks in advance!

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

(Paste the output of `pip freeze | grep slack`)

#### Python runtime version

(Paste the output of `python --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1.
2.
3.

### Expected result: 

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @joshight, thanks for asking the question!

If your app implements the Slack app OAuth flow and stores tokens in `InstallationStore`, you can expect that the user token for the user associated with an incoming request can be automatically resolved as `context.user_token`. If the user has not installed the app yet, `context.user_token` can be `None`. 

See also:
* https://github.com/slackapi/bolt-python/blob/v1.10.0/slack_bolt/authorization/authorize.py#L169-L215
* https://github.com/slackapi/bolt-python/blob/v1.10.0/slack_bolt/authorization/authorize.py#L269-L276
* https://github.com/slackapi/bolt-python/blob/v1.10.0/slack_bolt/middleware/authorization/multi_teams_authorization.py#L55-L68

If you want to reuse a single person's user token for any incoming request handling (I really don't recommend this, though), your app needs to run a query to fetch the user token from the apps' database.

Similarly, if your app does not implement the OAuth flow and you want to make a single user token accessible from any code in the app, you can set a user token value to an environment variable like `SLACK_ADMIN_USER_TOKEN` or so. But, again, for `search.*` API purpose, I really do not recommend sharing a user token with other members in a workspace (because the search results can include private channels and DMs!)

I hope this helps.

**Comment by joshight** [comment]
@seratch Thanks so much for the quick and helpful response. 

A little bit of additional info about my app - it's designed to only be used in channels and searches will be limited to only the channel where both the bot and user are, so I'm not as concerned about using a single user token. 

I should be able to use the **Bot User OAuth Token** from my app for this functionality, correct? 

Also, passing in the token as an environmental variable makes sense, but how do I actually use it to make the search_messages call within a listener function. 

My current code looks something like the following and I'm not sure how to get client to use a user token instead of the bot token (hope this makes sense): 
```

@APP.message('hi')
def handle_message(say, event, client, logger):
    results = client.search_messages(query=f'{message} in:{channel}', highlight=1, count=3)
```

Thanks again!

**Comment by seratch** [comment]
@joshight 

>I should be able to use the Bot User OAuth Token from my app for this functionality, correct?

No, the user token is **User OAuth Token**, which starts wth `xoxp-` prefix.

> how to get client to use a user token instead of the bot token

You can use `token` keyword argument as below:

```python
user_token = os.environ["SLACK_USER_TOKEN"]

@APP.message('hi')
def handle_message(say, event, client, logger):
    results = client.search_messages(
        token=user_token,
        query=f'{message} in:{channel}',
        highlight=1,
        count=3,
    )
```

**Comment by joshight** [comment]
Thanks again @seratch ! Very helpful info.

**Comment by picografix** [comment]
Helpful!
