### ISSUE TITLE
How do we support multiple developers working on the same app using socket mode?

### ISSUE THREAD

**Issue by plebuhn1** [slackapi/bolt-python#548]
- We support a slack app hosted as part of a flask app, uses bolt-python, and socket mode to connect to slack
- We have a number of developers that work on the app so each developer runs a local instance of the flask app and points to the app in a test workspace 
- When multiple developers are running local instances, slack distributes the requests randomly back to the local instances running, which makes concurrent development and testing impossible (as expected with socket mode).  Creating apps per developer also introduces complexity due to name collisions of the slash commands.  The only known workaround is for each developer to copy the app manifest, create their own app, and update a number of variables to avoid duplication of slash commands, however, this is very cumbersome and error prone.  

Are there any recommendation for developer environment setup to avoid the issues outlined above? We have to use socket mode for security purposes.

**Comment by seratch** [comment]
Hi @plebuhn1, thanks for writing in!

I do understand the pain point in your use case but we do not have any new information for you. 

Asking each developer to create a copy app for local development is the recommended way. After the App Manifest release, copying app config is far easier than the past but I do understand the pain point that you mentioned here. The only thing that I can add is to encourage developers to have their own testing workspaces rather than sharing a single workspace. This can be a workaround to avoid the slash command naming conflicts.

I know this is not an ideal answer for your question but I hope this helps.
