### ISSUE TITLE
Closing modal on button action with response_action=clear

### ISSUE THREAD

**Issue by kafejo** [slackapi/bolt-python#549]
Not sure if it's due to my last of understanding how this works but it seems that `respond_action = clear` doesn't close a modal.

My view:

```json
{
    "type": "modal",
    "callback_id": "plan-link",
    "title": {
        "type": "plain_text",
        "text": "Contribute",
        "emoji": true
    },
    "blocks": [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "You will be redirected to your browser for the checkout."
            },
            "accessory": {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "Open Checkout"
                },
                "action_id": "open-checkout",
                "url": "https://mycheckoutlink.com",
                "style": "primary"
            }
        }
    ],
    "close": {
        "type": "plain_text",
        "text": "Close",
        "emoji": true
    }
}
```

Then I observe the action like this:

```python
@app.action("open-checkout")
def handle_plan_link_opened(ack):
    ack(response_action="clear")
```

But the modal will not close. I'm banging my head against the keyboard at this point but cannot figure it out. Thanks for any help or suggestion!

**Comment by srajiang** [comment]
Hey there :wave: @kafejo.
```python
@app.action(“open-checkout”)
def handle_plan_link_opened(ack):
    ack(response_action=“clear”)
```
I suspect this is not working because you’re acknowledging a block_action, not a view_submission event. Here are the ways [to respond to block actions](https://slack.dev/bolt-python/concepts#action-respond) and they don’t look like what you’re trying to do here (i.e. close the modal).

As you can see in the diagram [in this modal flow ](https://api.slack.com/surfaces/modals/using#modifying), normally what might happen is a user interacts with an element in the view blocks, this triggers a block_action, and from the handler you can call views.update to update the state of the view. Closing the view is left up to the user. 

When the user decides to close the view (either through Close or Submit), your app gets that `view_submission` event, and simply by acknowledging it `ack()`, bolt takes care of closing the view.

The designers of Slack API `views.*` methods didn’t create a `views.close` API method which probably would be what you’d want to have in this instance. This was an intentional design choice to make sure end users could have standardized expectations for what will trigger a modal to close (either through hitting Submit or Close through the UI) .

My recommendation here would be to use  the `view.update` method in your “open-checkout” handler to update the contents of the view with a message saying something like “Looks like you’ve opened the checkout. You can safely close this window now!”

Hope this helps!

**Comment by kafejo** [comment]
I see, now I get it. Thanks for your help!
