### ISSUE TITLE
How to stop Bolt Application started using SocketHandler

### ISSUE THREAD

**Issue by ninad-mehta** [slackapi/bolt-python#558]
Hi All,

I am using Bolt Application from DataBricks notebook.
I start application using following code:

```python
handler = SocketModeHandler(app, socket_token)
handler.start()
```

Where I am providing my "xoxb" token in app configuration and "xapp" after enabling socket in socket_token.
Using above two command, I am able to start the application and send the alert messages to my desired Slack channel (using app.client.chat_postMessage).

However, I was not able to find any straightforward way to stop the handler (App) started using above code.
I tried to use dbutils.notebook.exit("0"), however it only exits the notebook, while the application keeps running in the background.
Is there any way I can use some slack bolt application code which I can use directly to stop the handler (Something like handler.stop())?

Thank you.

**Comment by seratch** [comment]
Hi @ninad-mehta, you can use `connect()` and `disconnect()` instead of `start()` method. These methods do not block your main thread while The `start()` method does.

* https://github.com/slackapi/bolt-python/blob/v1.11.1/slack_bolt/adapter/socket_mode/base_handler.py#L29-L39
* https://slack.dev/bolt-python/api-docs/slack_bolt/adapter/socket_mode/base_handler.html#slack_bolt.adapter.socket_mode.base_handler.BaseSocketModeHandler

When you completely terminate a `SocketModeHandler` instance, you can use `close()` method. This method is similar to the `disconnect()` method but it cleans up all the internal states/resources of the `SocketModeHandler`. After calling this, the `SocketModeHandler` instance is no longer useable.

I hope this helps!

**Comment by ninad-mehta** [comment]
Seems like there was no need to start the socket at all to send alert messages to slack. Got rid of that code and its working fine.
Thank you Seratch for your response.

**Comment by ChrisHills463** [comment]
Sorry to bring up a closed thread, but I thought it better to keep discussion relevant where an issue already exists rather than opening a new one.

I have found that the SocketModeHandler still blocks the main thread and I am unable to cleanly exit my script. Example:-

```python
import os
import threading
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET"),
)
handler = SocketModeHandler(app, app_token=os.environ.get("SLACK_APP_TOKEN"))
logger.debug("Connecting to Slack...")
handler.connect()
logger.debug("Connected!")
while True:
    try:
        threading.Event().wait()
    except KeyboardInterrupt:
        break

logger.debug("Shutting down...")
handler.close()
logger.debug("Finished")

for thread in threading.enumerate(): 
    print(thread.name)
```

Shows the output (abbreviated):-

```
2024-02-23 14:53:06 DEBUG [MainThread] Connected!
[^C]
2024-02-23 14:53:11 DEBUG [MainThread] Shutting down...
2024-02-23 14:53:13 DEBUG [MainThread] Finished
MainThread
Thread-1 (_run)
```

If we look in https://github.com/slackapi/bolt-python/blob/main/slack_bolt/adapter/socket_mode/base_handler.py#L57 we can see that it will call `Event().wait()` and there appears to be no mechanism to break this loop and cause the program to end.
