### ISSUE TITLE
Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}}) --- [Suggestion] You can handle this type of event with the following listener function:

### ISSUE THREAD

**Issue by utsang** [slackapi/bolt-python#562]
I wanted to test my script with a simple message and I get the error mentioned in the title, my main goal is to read what the user has sent in the main chat and then send the open and close price of a given stock using yfinance. I was also having hard time finding the home page for my server as I tried one of the example code given in the documentation and I don't see if being dispalyed any where in my channel, do I need to make a new channel for that.

### CODE:

```bash
load_dotenv()
env_path = Path('.')/ '.env'
load_dotenv(dotenv_path=env_path)
app = Flask(__name__)

app = App(
    token=os.environ.get("SLACK_TOKEN"),
    signing_secret=os.environ.get("SIGNING_SECRET")
)

if __name__ == "__main__":
    app.start(port=int(os.environ.get("PORT", 3000)))


@app.message("knock knock")
def ask_who(message, say):
    say("_Who's there?_")

```

I am also running the ngrok local server as well, I am very new to this so most of the documentation was confusing to me

**Comment by misscoded** [comment]
Hi @utsang! Apologies that you've found the documentation confusing. Let's see if we can work out a solution for what you're trying to do here.

First, you want to make sure that your listeners (`@app.message`) come _before_ the logic that encapsulates `app.start()`. That is what's causing the error that you're seeing.

From a design and maintainability perspective, I would recommend perhaps considering a different user experience for looking up stock prices. There are _many_ possible stocks that a user could be interested in, and to create a listener that knew when to execute _only_ in that context (and not when they were simply talking about stocks) might be tricky. Instead, **I'd suggest instead of a message listener that you incorporate a command. For example, a user could run the command: `/price CRM` to return the price(s) of CRM.**

I've created a working implementation of the above approach and included it below for reference. **Don't forget: you'll need to add the command to your application in the App Configuration ([Bolt docs](https://slack.dev/bolt-python/concepts#commands), [API docs](https://api.slack.com/interactivity/slash-commands)).** Since you had included Flask in your snippet, I've taken the Flask approach, as well:

```
import logging

logging.basicConfig(level=logging.DEBUG)

from slack_bolt import App
from slack_bolt.adapter.flask import SlackRequestHandler
from flask import Flask, request
from dotenv import load_dotenv

load_dotenv()

app = App()
flask_app = Flask(__name__)
handler = SlackRequestHandler(app)

@app.command('/price')
def get_stock_price(ack, client, respond, command):
  ack()
  
  symbol = command['text'] # TODO: validate symbol
  curr_price = '5.04' # TODO: make API call to get stock price
  
  # Option 1: Send requested stock price to user, in channel, as 
  # an ephemeral message (a message only they can see)
  respond(f"Current price for {symbol} is: {curr_price}")

  # Option 2: Send requested stock price directly to user via DM
  user_id = command['user_id']
  client.chat_postMessage(channel=user_id, text=f"Current price for {symbol} is: {curr_price}")

@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
  return handler.handle(request)

if __name__ == "__main__":
  app.start(3000)  # POST http://localhost:3000/slack/events
```

I've included two options by which you can deliver the stock price to the user: in the same channel, as an ephemeral message that only they will see, or via DM. The benefit of a DM is that users can "hold onto" the messages and refer to them later. I'm not sure if that's important in your use case, so I leave it up to you to decide which is best.

As for the "home page for your server", can you clarify what you mean? Do you mean a separate page outside of Slack, in the browser? You mention expecting it to be displayed in the channel, so I'm not sure. Some more detail on this would be useful.

**Comment by utsang** [comment]
Thank you very much for responding, as for the command part, this is sort of a side project that I was working on so I was thinking as long as the user inputs the Ticker symbol thats listed on the broker I send the info, since I need to get that value is there a command, can I use b =  event.get('text') in this case or is there a specific way? The DM feature is very cool and I'll look to implement it later but for now I just wanted way to extract what the user has typed in, I am assuming that the user will only talk about tickers and use the correct format and will use a specific channel. For the Home page issue, I was just confused as to what slack would consider home page lol, I made the testing server and did not specify any home channel, so when I was trying out the python decorator example, I did'nt know where to find any changes I would have made to the decorator, Hope that makes sense. 
I have added image below:
![image](https://user-images.githubusercontent.com/8095867/148147013-d1fa970c-5115-4728-b170-b2cef2c994d7.png)

**Comment by utsang** [comment]
to get the stock price, Im using yfinance which downloads the said ticker and converts it into a .csv file and I get relevant information from the pandas df

**Comment by misscoded** [comment]
> since I need to get that value is there a command, can I use b = event.get('text') in this case or is there a specific way?
> I am assuming that the user will only talk about tickers and use the correct format and will use a specific channel

If you mean that you want to listen for **all** messages that the user sends, we recommend using the `@app.event('message')` listener, accessing the message text as seen below:

```
@app.event('message')
def print_message(event):
  msg_txt = event['text']
  print(msg_txt)
```

To note: these message listeners will also pick up messages sent by apps, so if you want to filter those out, you can write some additional logic and return early if the event has a subtype of `bot_message`.

> For the Home page issue, I was just confused as to what slack would consider home page

Usually, we think of the Home Tab as the "home page" for apps. This is where your users can find all useful and pertinent information related to your app. You can learn more about the Home Tab [here](https://slack.dev/bolt-python/concepts#app-home). 

As for a "home channel", it's entirely up to you which channel(s) you add your bot to! 🙂 

> Also is there a way use the text that user types in outside of the function as well? I am very new to coding as well

You can definitely do so! One way to accomplish this is by using a helper function. This allows you to pass the message text elsewhere (outside of the listener function) to process. 

The below snippet is an edit of the above and might be a good place for you to start from:

```
@app.event('message')
def print_message(event):
  msg_txt = event['text']
  do_something(msg_txt)

def do_something(text):
  print(f"Doing something with {text}!")
```

Let us know if the above resolves the issue(s) raised!

**Comment by utsang** [comment]
Thank you very much for responding, I think this answers most of my questions. So I have the following code:

```
tickerWant = text
data = yf.download(tickerWant, start="2021-09-5", end=d4)
    
data.to_csv(rf'C:\work\demo\data\{tickerWant}.csv')
```
in my case I want tickerWant to be whatever the ticker the user sends, so I can just do this correct:

```
def do_something(text):
      tickerWant = text
      data = yf.download(tickerWant, start="2021-09-5", end=d4)
      data.to_csv(rf'C:\work\demo\data\{tickerWant}.csv') 
```


and then use the def print_message function?
