### ISSUE TITLE
Heroku Automatic Dyno Restarts Causing Slack Oauth Credentials to "fail"

### ISSUE THREAD

**Issue by daneasterman** [slackapi/bolt-python#573]
I have successfully deployed my Slack app (RoboStox) to Heroku for public distribution. (But not submitted to Slack app store).

The problem is that according to Heroku they automatically restart their dynos every 24hrs, see here: [https://devcenter.heroku.com/articles/dynos#automatic-dyno-restarts](https://devcenter.heroku.com/articles/dynos#automatic-dyno-restarts). 

I can clearly see this in the Heroku logs in the screenshot below, for example where it says: "**state changed from starting to up"**:

<img width="532" alt="Screenshot 2022-01-08 at 15 10 16" src="https://user-images.githubusercontent.com/4712052/149502146-3123689e-515e-4efe-ab23-fbb280b94484.png">

This causes the user to receive the error message  in screenshot below:

<img width="408" alt="Screenshot 2022-01-14 at 10 26 25" src="https://user-images.githubusercontent.com/4712052/149500577-8e3c213b-641d-44d0-9d7a-28363db41ea3.png">

When I look at Heroku logs I can see that the error message is: `auth.test API call result is unexpectedly None`. This issue has been resolved in this ticket here: [https://github.com/slackapi/bolt-python/issues/474](https://github.com/slackapi/bolt-python/issues/474) which is due the stored OAuth installation being lost.

So my conclusion from this is that the Heroku dyno restart is causing the oauth credentials to be lost or reset. 

My OAuth code in my app is taken from the official Slack Python Bolt docs here: [https://slack.dev/bolt-python/concepts#authenticating-oauth](https://slack.dev/bolt-python/concepts#authenticating-oauth) and works in my local development environment:

```
oauth_settings = OAuthSettings(
    client_id=SLACK_CLIENT_ID,
    client_secret=SLACK_CLIENT_SECRET,
    scopes=["chat:write", "commands", "chat:write.public"],
    installation_store=FileInstallationStore(base_dir="./data/installations"),
    state_store=FileOAuthStateStore(expiration_seconds=600, base_dir="./data/states")
)
app = App(signing_secret=SLACK_SIGNING_SECRET, oauth_settings=oauth_settings)
handler = SlackRequestHandler(app)
```

What can I do to resolve this issue?

Many thanks in advance for your help!

#### Slack SDK Versions:
slack-bolt==1.4.4
slack-sdk==3.4.2
slackeventsapi==3.0.0

#### Python runtime version:
Python 3.9.6

#### OS info:
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H1417

**Comment by seratch** [comment]
Hi @daneasterman, thanks for asking the question!

We don't recommend using `FileInstallationStore` and `FileOAuthStateStore` for production-grade apps. If you scale out your app (= running multiple instances behind Request URL), the installation data won't be shared among the app instances. Specifically talking about your use case with Heroku, the Heroku platform does not guarantee persistent file storage for your app instances. That's why you've lost the installation data.

Instead, you can use either a relational database or Amazon S3 for storing installation data. Perhaps, using PostgreSQL add-on in Heroku would be the most straightforward way.

I've published an example app using SQLAlchemy + PostgreSQL here:
https://github.com/seratch/send-it-later-for-slack#heroku-deployment

For more information about how to use Heroku / PostgreSQL in general, please refer to Heroku's documentation.

I hope this helps!

**Comment by seratch** [comment]
@daneasterman 
This is not built-in support but I've implemented an example in the past. If you want to use it in your app, please feel free to use the implementation.

* https://gist.github.com/seratch/d81a445ef4467b16f047156bf859cda8
* https://gist.github.com/milen-yordanov/966a81790b183e48a2831aeec323f550

Can we close this issue now?

**Comment by daneasterman** [comment]
Also just one more thing to confirm @seratch - the example app you provided will scale to multiple Slack installation instances right? (for public distribution outside a specific workspace).

I concluded from you first answer that storing the OAuth data in the file system will not do this?

**Comment by seratch** [comment]
As I already mentioned above, you don't need to worry about it as long as you use a single production-grade database that is accessible from your Bolt app instances.

**Comment by daneasterman** [comment]
Thanks, much appreciated!
