### ISSUE TITLE
Options loaded from a url are not filtering on characters typed

### ISSUE THREAD

**Issue by r4ibOm** [slackapi/bolt-python#606]
Hello,

I created a modal and an item in the modal is a selection input, of the type "external_select" that looks for a list of options.

I did it as described in the documentation and the list with all the items appears when I click on the listbox. The problem is that when the user starts typing, instead of filtering by the characters typed, it is always showing all the options.

``` python
from slack_utils.main import app


@app.shortcut("requisicao_id")
def handle_shortcuts(ack, body, client):
    # Acknowledge the command request
    ack()
    # Call views_open with the built-in client
    client.views_open(
        # Pass a valid trigger_id within 3 seconds of receiving it
        trigger_id=body["trigger_id"],
        # View payload
        view={
            "type": "modal",
            # View identifier
            "callback_id": "view_1",
            "title": {"type": "plain_text", "text": "My App"},
            "submit": {"type": "plain_text", "text": "Submit"},
            "blocks": [
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": "Welcome to a modal with _blocks_"},
                    "accessory": {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "Click me!"},
                        "action_id": "button_abc"
                    }
                },
                {
                    "type": "input",
                    "block_id": "input_c",
                    "label": {"type": "plain_text", "text": "What are your hopes and dreams?"},
                    "element": {
                        "type": "plain_text_input",
                        "action_id": "dreamy_input",
                        "multiline": True
                    }
                },
                {
                    "type": "input",
                    "element": {
                        "action_id": "aws_access_select",
                        "type": "external_select",
                        "placeholder": {
                            "type": "plain_text",
                            "text": "Select or enter the expected value..."
                        },
                        "min_query_length": 0
                    },
                    "label": {
                        "type": "plain_text",
                        "text": "Label",
                        "emoji": True
                    }
                }
            ]
        }
    )


@app.view("view_1")
def handle_view_events(ack, body, client, view, logger):
    # Assume there's an input block with `input_c` as the block_id and `dreamy_input`
    hopes_and_dreams = view["state"]["values"]["input_c"]["dreamy_input"]["value"]
    user = body["user"]["id"]
    # Validate the inputs
    errors = {}
    if hopes_and_dreams is not None and len(hopes_and_dreams) <= 5:
        errors["input_c"] = "The value must be longer than 5 characters"
    if len(errors) > 0:
        ack(response_action="errors", errors=errors)
        return
    # Acknowledge the view_submission request and close the modal
    ack()
    # Do whatever you want with the input data - here we're saving it to a DB
    # then sending the user a verification of their submission

    # Message to send user
    msg = ""
    try:
        # Save to DB
        msg = f"Your submission of {hopes_and_dreams} was successful"
    except Exception as e:
        # Handle error
        msg = "There was an error with your submission"

    # Message the user
    try:
        client.chat_postMessage(channel=user, text=msg)
    except e:
        logger.exception(f"Failed to post a message {e}")


@app.options("aws_access_select")
def handle_some_options(ack):
    options = [
        {
            "text": {
                "type": "plain_text",
                "text": "Developer"
            },
            "value": "1"
        },
        {
            "text": {
                "type": "plain_text",
                "text": "Homologation"
            },
            "value": "2"
        },
        {
            "text": {
                "type": "plain_text",
                "text": "Production"
            },
            "value": "3"
        },
        {
            "text": {
                "type": "plain_text",
                "text": "Security"
            },
            "value": "4"
        },
        {
            "text": {
                "type": "plain_text",
                "text": "Cloud"
            },
            "value": "5"
        }
    ]

    ack(options=options)
```
As you can see, all items are always listed regardless of the value entered.:
![image](https://user-images.githubusercontent.com/44219005/156066459-3887b7c2-fe8b-4537-9d2a-3577556b6da5.png)

**Comment by filmaj** [comment]
Hey @r4ibOm !

Thanks for writing in. To get filtering working properly, the key is to integrate the filtering logic in your `handle_some_options` handler - the `@app.options` decorated function. All middleware and listener methods, including the `@app.options` ones, have access to [a variety of arguments](https://slack.dev/bolt-python/api-docs/slack_bolt/kwargs_injection/args.html). Your handler uses only one so far: the `ack` method. However, in your case, since you want to filter on what the user is typing, you will want to also inspect the `body`, `options` or `payload` argument(s) as well (all three of these arguments should be identical in this particular situation, as you can see by [this test code in bolt-python](https://github.com/seratch/slack_learning_app_ja/blob/f3b4ae86511f8bc1397db0641338948b5e4c6538/app/tutorials.py#L1027-L1053)). My colleague @seratch has a really nice learning application that uses bolt-python, and you can see him implementing [this exact filtering logic in a particular area of his application](https://github.com/seratch/slack_learning_app_ja/blob/f3b4ae86511f8bc1397db0641338948b5e4c6538/app/tutorials.py#L1027-L1053) - I hope this example is useful to you. Specifically, `body.get("value")` is inspected, and if it exists, some filtering logic is applied to the returned options. If `body` does not contain `value`, then all options returned.

I think I will tweak our documentation in Bolt-Python around listening and responding to options to try to provide more hints as to how to do this.

Let me know if this is helpful to you! If so, and this issue is resolved for you, please kindly close the issue. If not, we are here to help!

**Comment by r4ibOm** [comment]
@filmaj 

Thanks a lot for the help. I thought the filter was done automatically. With this example I managed to do it the way I want.

It would be very helpful for other developers to add this information to the documentation.

Thanks.
