### ISSUE TITLE
Lazy listener not working as intended when deployed to AWS Lambda as a container

### ISSUE THREAD

**Issue by imageschool** [slackapi/bolt-python#630]
**Issue**

**(History)**
_(AWS  lambda deployment with project .zip file archive )_

I was previously able to solve lazy listener issue (#615) thanks to @seratch 
By removing async and correctly using AWS lambda SlackRequestHandler

**(Current)**
_(AWS lambda deployment with container image)_

Because of Lambda quota (250MB unzipped), I have decided to deploy the same app as a container image.

But when deployed as a container image, I am again having a problem with Lambda lazy listener that not being executed to the end of the function and just timeout.

![image](https://user-images.githubusercontent.com/29969006/161949919-6e80cd1e-432b-4472-94bb-0089c7f909a9.png)

### Reproducible in:
- Clone main branch of https://github.com/imageschool/slack-bolt-python-aws-lambda-error-example/tree/main
- Building Docker image and push to AWS ECR then update AWS Lambda function

_Dockerfile_
```
##./Dockerfile
FROM public.ecr.aws/lambda/python:3.9

# Workdir
WORKDIR ${LAMBDA_TASK_ROOT}

# Install the function's dependencies using file requirements.txt from your project folder.
COPY requirements.txt  .
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copy all src files
COPY . .

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "main.handler" ]
```

_Deployment Script_
```
project_name="your-project-name"
version="v1"
repository="your-ecr-repository-address"

echo "------------------------------------------------------------------"
printf "Docker Building $project_name:$version...\n"
echo "------------------------------------------------------------------"
docker buildx build --platform linux/amd64 -t $project_name:$version .

echo "------------------------------------------------------------------"
printf "AWS Login & Create Repository...\n"
echo "------------------------------------------------------------------"
aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $repository
aws ecr create-repository --repository-name $project_name --image-scanning-configuration scanOnPush=true --image-tag-mutability MUTABLE

echo "------------------------------------------------------------------"
printf "Docker Tagging & Pushing to AWS ECR...\n"
echo "------------------------------------------------------------------"
docker tag  $project_name:$version $repository/$project_name:$version
docker push $repository/$project_name:$version

echo "------------------------------------------------------------------"
printf "AWS Lambda Function Updating...\n"
echo "------------------------------------------------------------------"
aws lambda update-function-code --function-name $project_name --image-uri $repository/$project_name:$version
```

#### The `slack_bolt` version

slack-bolt==1.11.1
slack-sdk==3.13.0

#### Python runtime version

Python 3.9.7

#### OS info

ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @imageschool, is your handler function really called? Do you see [this logging](https://github.com/imageschool/slack-bolt-python-aws-lambda-error-example/blob/dab4f3806d4de5f2bbc0edc051e0d4547c2f2071/main.py#L18)? I don't see it in the screenshot that you've shared.

Also, I would suggest adding info logging in the beginning of the method? https://github.com/imageschool/slack-bolt-python-aws-lambda-error-example/blob/dab4f3806d4de5f2bbc0edc051e0d4547c2f2071/main.py#L61-L63

```python
def handler(event, context):
    logger.info(f"handler method is called with {event}") # ADDED
    app_handler = SlackRequestHandler(app=slack_app)
    return app_handler.handle(event, context)
```

I hope that you will figure the cause out soon.

**Comment by imageschool** [comment]
Yes I can see both logger and handler logs
![image](https://user-images.githubusercontent.com/29969006/161957267-7f8e2db7-5830-4e38-b5a2-d661851c4673.png)

"logger enabled" is capital in this log because I am screen capturing on my main project right now (basically they are the same structure)

**Comment by seratch** [comment]
@imageschool Thanks for sharing a bit more details. Let me share a few comments:

* I don't see any logs related to the lazy listener invocations. This indicates:
  * Your container may not have the access to credentials with sufficient permissions to invoke a new lambda function and the lazy listener invocation might silently result in an error. If this is correct, the bolt-python's error logging can be improved to provide more information to developers.
  * Can you double-check the AWS credentials that your container can access?
* The lambda invocation takes 2.5 seconds (3 second timeouts may occur if you operate this service in production)
  * This indicates the cold-start overhead (perhaps due to 250MB+ module loading?) is not ignorable
  *  I don't recommend going with the FaaS architecture for this use case. Enabling [reserved concurrency](https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html) or switching to ECS / EKS would be great options

Since I am in Asia Pacific timezone, I will be offline at least for a half day.

**Comment by imageschool** [comment]
Thanks for the comments!

I am not sure what you are referring to regarding AWS credentials. Do you mean lambda:invokefunction / lambda:getfunction permissions? I have set them as below.

![image](https://user-images.githubusercontent.com/29969006/162117565-6380a3ce-4007-4c6e-b056-a1bc189eef63.png)

To find out lazy method invocation, I set debug logs as below

```
# Register listener
app.action(ACTION_CREATE_SERVICE)(
    ack=just_ack,
    lazy=[action_create_service]
)
```
![image](https://user-images.githubusercontent.com/29969006/162118055-7adeef5a-36c3-473e-ab5f-870888fdf821.png)


Lazy method gets invoked but it lambda just ends right after it starts (see below log)
![image](https://user-images.githubusercontent.com/29969006/162117945-464d2313-1485-4b8f-bd3a-a16b003da395.png)

**Comment by seratch** [comment]
@imageschool 
> Do you mean lambda:invokefunction / lambda:getfunction permissions? I have set them as below.

Yes, I do. 

According to the information that you just shared, the lazy listener mechanism is correctly working.

Perhaps, the issue is caused by our timeout settings. I see "task timed out after 10.01 seconds" in the log. This indicates that your lambda execution timeout is set to 10 seconds. Refer to https://stackoverflow.com/questions/43577746/aws-lambda-task-timed-out and other resources for more details.

Since the issue here can be related to your AWS configuration, we won't be able to provide further supports for it. Would you mind closing this issue?

**Comment by imageschool** [comment]
> @imageschool
> 
> > Do you mean lambda:invokefunction / lambda:getfunction permissions? I have set them as below.
> 
> Yes, I do.
> 
> According to the information that you just shared, the lazy listener mechanism is correctly working.
> 
> Perhaps, the issue is caused by your timeout settings. I see "task timed out after 10.01 seconds" in the log. This indicates that your lambda execution timeout is set to 10 seconds. Refer to https://stackoverflow.com/questions/43577746/aws-lambda-task-timed-out and other resources for more details.
> 
> Since the issue here can be related to your AWS configuration, we won't be able to provide further supports for it. Would you mind closing this issue?

Right, I will look into that. Thanks!
