### ISSUE TITLE
get ordered message events

### ISSUE THREAD

**Issue by juliocanares** [slackapi/bolt-python#668]
Hi 👋
My use case with slack events is to create a message forwarding tool, basically if you send messages to a channel `a` it will be redirected to channels `x`, `y` and `z` for example, the issue is that if the user in channel `a` sends multiple messages quickly `1`, `2`, `3`, `4`, the other channels will get the messages in a different order like `4`, `2`, `1`, `3` which disrupts context.
I guess this is due to how webhooks work and the congestion that can be hitting the server.
but is there a way to tell the slack api to ensure the order of these messages?

I also saw that slack rtm api could help here, but my app is not a classical one so I wouldn't be able to use the rtm api in this case right or I can combine the events api with the rtm?

Thank you

#### The `slack_bolt` version
1.7.0

#### Python runtime version
3.8.2

**Comment by srajiang** [comment]
Hi @juliocanares - Thanks for writing in with this question! Can you give more details on how your app is currently setup and which packages you're using for your use case?

**Comment by juliocanares** [comment]
I am using flask 1.1.2 as a web framework and slack bolt 1.7.0. My slack app is a modern one (not classic) and I just initialize the slack bolt app and start listening for message events. do you any more specific thing?

**Comment by neptunel** [comment]
Hi @juliocanares, thank you for providing additional info. Your guess about how webhooks work and the congestion hitting the server was correct. We don't have a specific method in our APIs or SDKs to guarantee that messages are sent in order. But your issue can be handled with a change of design in your way of forwarding messages. I'm guessing you're listening to messages on channel ` a`, and creating a new one with the same message body, and sending it to the forwarded channels using chat.postMessage(). 

Have you considered using a queue-type structure in the memory? You can put the messages on the queue as jobs when your app receives them from channel ` a` and then one by one dequeue them to send to the other channels in order. When your app received a response code that the previous chat.postMessage() call was successful, you can send the next message of the queue.

Also, when a person edits their message that's a[ new event](https://api.slack.com/events/message/message_changed) and you may have to consider it as an edge case and redesign your solution.

If you find this helpful, feel free to close this issue.

**Comment by juliocanares** [comment]
@neptunel thank you for the response that is actually a good suggestion. For what I've read in the slack docs I may be able to use RTM api to ensure the order of the messages as stated in the [documentation](https://api.slack.com/faq#events_api), what do you think about it? and will it be possible to use the events api (I am using it for slash commands) combined with the RTM api?
<img width="933" alt="image" src="https://user-images.githubusercontent.com/5007653/173138041-810e81e6-c1c7-4b3f-85bb-c327bbb88c98.png">

**Comment by srajiang** [comment]
@juliocanares - Can you use RTM API to ensure the order of messages sent is the order that is received by Slack and posted? Yes, but I would only consider using this if this is really the only requirement you have for your use case. 

Can you use Events API and RTM API together in one app? No. Unfortunately, you can't use Events API and RTM API combined in this way, because RTM API requires that your app be a classic one whereas Events API is based on the modern permissions model we recommend devs to follow.

You can also consider making a call to [conversations.history](https://api.slack.com/methods/conversations.history) to fetch your forward-to channels histories and cross check against the sent messages - could be a little hairy and require many API calls, which is why I think @neptunel's suggestion to use a queue is what I'd suggest as well.
