### ISSUE TITLE
Failed to check the state of sock (session id: XXX, error: BrokenPipeError, message: [Errno 32] Broken pipe)

### ISSUE THREAD

**Issue by opikalo** [slackapi/bolt-python#675]
### Reproducible in:
slack-bolt==1.14.0
slack-sdk==3.17.0
Python 3.7.4
#102~16.04.1-Ubuntu SMP Mon May 11 11:38:16 UTC 2020

#### The `slack_bolt` version
slack-bolt==1.14.0
slack-sdk==3.17.0

#### Python runtime version
Python 3.7.4

#### OS info
#102~16.04.1-Ubuntu SMP Mon May 11 11:38:16 UTC 2020

#### Steps to reproduce:
The application is running using socket mode. 
```
if __name__ == "__main__":
    handler = SocketModeHandler(app, SLACK_APP_TOKEN)
    handler.start()

```
Occasional, absolutely spontaneous, approximately once a day type of failure (see sentry stack trace for details)
`Failed to check the state of sock (session id: b330e7f3-86b5-424b-8925-f4a9911afee8, error: BrokenPipeError, message: [Errno 32] Broken pipe)`

### Expected result:

Expected to not have spontaneous drop outs like that

### Actual result:

We keep getting a trickle of those errors. Sometimes on launch. Sometimes after a long time of running. 
Mainly looking to see if I'm missing some kind of setup/retry/ health checks in order to avoid it.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @opikalo, thanks for writing in!

This can be caused by any network glitch on your end (or somewhere between your app and Slack). Can you check my response to a similar question here - https://github.com/slackapi/bolt-python/issues/605#issuecomment-1054690964 ? As long as the Socket Mode client app automatically reconnects as necessary and continues to work without restarting the process, you can ignore those error log lines for now.
