### ISSUE TITLE
The last word of the message gets lost when posted with iPhone 8, XR.

### ISSUE THREAD

**Issue by cnr0724** [slackapi/bolt-python#676]
#### The `slack_bolt` version

slack-bolt==1.13.0
slack-sdk==3.15.2
slacker==0.14.0
slackeventsapi==3.0.1

#### Python runtime version

Python 3.8.8

#### OS info

Ubuntu-20.04.1

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Post a message in a channel where the app is integrated in with iPhone 8 or iPhone XR.

### Expected result:

The whole message is received by the slack app.

### Actual result:

The last word of the message vanishes.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by cnr0724** [comment]
- Is the same message, in its entirety, displayed correctly on devices other than iPhone 8 / iPhone XR?

Actually the same situation sometimes happens when the message is posted by PC slack of Windows. But usually, the same message is displayed correctly on Android devices (Galaxy note 10 and other devices) or other PC slack (Ubuntu 20.04.1, and Windows when it's lucky).
- What is the message that is being sent (character count, content)?

Usually the character count is about 10 texts length, and the content is the combination of Korean and English.
The example would be 'ㄱㄱ project'. When this kind of message is posted, the slack app only receives the 'ㄱㄱ' part. I've checked the log and the 'project' part vanishes.
- Is this behavior seen regardless of the content of the message?

Yes. But I haven't tested what happens when the first word differs.
- Is this behavior seen regardless of the character count of the message?

Yes. As the lengths of the project name are various, the character count of the message varies. But I haven't tested what happens when the message consists of more than 3 words.

**Comment by misscoded** [comment]
Thanks for giving providing us with all of that information! It will hopefully help us narrow down what's going on here. From what you've explained, it seems to be tied to the presence of Korean characters preceding the English words, but it's hard to be sure at this point.

I'm going to see what I can find by way of known issues, but in the meantime, can you take a few minutes to try out different combinations and lengths of words so that we can get a clearer picture of when the issue arises? For example:

- Messages that have more than three words
- Messages that follow different order patterns ([English, Korean, English], [Korean, English, Korean], etc.)

**Comment by cnr0724** [comment]
- Messages that have more than three words
- Messages that follow different order patterns ([English, Korean, English], [Korean, English, Korean], etc.)

So I've tried 'test 테스트', '테스트 test 테스트', and 'test 테스트 test 테스트'. All tests worked out.

I guess vanishing event only happens when the message is in the format of 'Korean English'.
