### ISSUE TITLE
How to go about e2e testing for a Bolt app?

### ISSUE THREAD

**Issue by gangfang** [slackapi/bolt-python#681]
[This is a question]

Hi, what would you recommend to do when we implement e2e tests for a Bolt app in socket mode if we don't want to touch the UI at all (e.g., not using cypress.io)? The challenge is there doesn't seem to be a way to send our app test events because of our app's WebSocket connections are directed to Slack server.

**Comment by gangfang** [comment]
Thank you so much @seratch!

I am going through them and have these questions:

1. are they merely example tests or are they actually used? I am asking this because I am not seeing those classes (e.g., `TestEventsSocketMode`) are referenced anywhere
2. are they tests for the Bolt framework itself or applications built on top of the framework? 
3. still looking. will edit

**Comment by seratch** [comment]
@gangfang 

>looks like they are tests for the Bolt framework itself instead of applications built on top of the framework. How do you think they can be helpful for e2e testing for my own app?

You can reuse the way especially in the scenario tests. Those tests verifies how an `app` works with a specific payload data with predefined listeners, not the internal module inside the framework. 

>Our end goal is still to test our app in the wild/testing env e2e (either including the UI or not), but the simulation of interactions mocks our app, how the above goal can still be achieved?

Precisely speaking, indeed those tests are not end-to-end tests. It's more like a scenario test without real Slack API server involvement. If it is not the one you are looking for, probably you can go with a different solution. As mentioned above, we don't have any great suggestion for it at this moment, though.

>are they merely example tests or are they actually used? I am asking this because I am not seeing those classes (e.g., TestEventsSocketMode) are referenced anywhere

Since they are pytest test classes, they are not referenced from any others. You can run those by pytest command.

Probably, I've answered all the questions and I don't have any further suggestions here. Would you mind closing this issue now if you don't have any follow-ups?

**Comment by gangfang** [comment]
Thank you @seratch for your answers!

Please close!
