### ISSUE TITLE
Can I reuse a single client object for each event?

### ISSUE THREAD

**Issue by roeniss** [slackapi/bolt-python#697]
Hi, I'm trying to make a slack bot in OOP-fashioned way.

```pyhotn
@app.event('reaction_added')
def handle_reaction_added_event(ack, say, event, client):
    ack()
    eventHandler.run(client, say, event)


class EventHandler:
    def run(self, web_client: WebClient, say: Say, event: Dict[str, Any]):
        obj_a = A(web_client)
		obj_b = B(say, obj_a)
		obj_c = C(event, obj_b)

		# work with those objects
```

As seen above, everytime I get event from slack I inject `client`, `say`, `event` object to my handler.

In handler, I made up some object with them. Everytime.

So my question is, can I reuse my client when first event came in, and use it for later event?

In short, **I want some singletone objects that have slack_bolt arguments.**

Below is what I want to make:

```python

@app.event('reaction_added')
def handle_reaction_added_event(ack, say, event, client):
    ack()
    eventHandler.run(event) # client, say are already injected somehow

class EventHandler:
    def run(self, event: Dict[str, Any]):
		obj_c = C(event, obj_b) # obj_b is singleton

        # ...
```

#### The `slack_bolt` version

slack-bolt==1.14.3

#### Python runtime version

3.9.13

#### OS info

ProductName:    macOS
ProductVersion: 12.5
BuildVersion:   21G72
Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000

**Comment by seratch** [comment]
Hi @roeniss, thanks for writing in.

First off, I personally don't recommend trying to reuse/cache those argument data. Doing so will make your code harder to maintain and can cause unexpected behaviors. Also, if the primary reasons why you are planning to do is the improvement of runtime performance, I don't think that it can be so beneficial because those argument instances are created for each request even when you have the cache data of them. Also, bolt-python can run fast enough.

Although above is my basic stance, I am happy to answer your questions here:

>So my question is, can I reuse my client when first event came in, and use it for later event?

Caching `client` and `say` instances can work as long as your app matches all of the following:

* Your app accepts a single bot token when initializing the `App` instance. In other words, your app  does not enable the Slack OAuth flow (= enabling multiple workspaces to use the same app)
* Your app does not enable the token rotation: https://api.slack.com/authentication/rotation

Contrarily, you should not reuse the `event` data. Every single `event` data is different. Trying to reuse can cause race condition and/or data corruption issues.

I hope this was helpful to you. If everything is clear, would you mind closing this issue?

**Comment by roeniss** [comment]
Thank you @seratch, your comment really helped me a lot.
Actually, I didn't think about performance, but readability and cleanness of the code. The way that I inject dependencies for each request makes me a little nervous. Maybe I'm familiar with java and spring's singleton pattern? I don't know..
Anyway, I'll try other designs. Thank you for such a kind reply!
