### ISSUE TITLE
How can I forward an image from an older message without making the image public?

### ISSUE THREAD

**Issue by ArturFortunato** [slackapi/bolt-python#702]
I created a slash command that will send images from older messages. But I couldn't find a way to send such images without making them public. I know this is possible because I can do it manually.  How can this be achieved?

### Reproducible in:

More of a generic question, no need to reproduce anything

#### The `slack_bolt` version

slack-bolt==1.14.0
slack-sdk==3.17.2

#### Python runtime version

Python 3.10.5

#### OS info

ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101

#### Steps to reproduce:

Don't need to reproduce anything

### Expected result:

I should be able to forward images from previous messages (in public channels) without making the image public

### Actual result:

The message/preview doesn't work (no errors, they just don't appear), which forces me to make the image public.

**Comment by WilliamBergamin** [comment]
Hi @ArturFortunato thanks for writing in!

Have you tried sending your image as a file along with a comment with the [file upload method](https://api.slack.com/methods/files.upload)?

**Comment by ArturFortunato** [comment]
Hello @WilliamBergamin , thank you for your answer! 😄 

Is there a way to do it using Bolt directly? 

I haven't tried that option, but I will and share results!

**Comment by filmaj** [comment]
Hey @ArturFortunato, can you provide some code to help me get setup with experimenting how to do this? It would be good to know how you are getting a reference to the previously-uploaded images.

**Comment by ArturFortunato** [comment]
Hey @filmaj, sorry to take so long to answer :) 

So:
* Once an image is uploaded, I (can) store all the fields send in the event


* On a slash command event, I show a `view` with the image
client.views_open(
        trigger_id=command["trigger_id"],
        view=SlackService.get_image_preview_view(image_url, query_metric.id, len(query_metric.query_result_ids) == 1),
    )
* If the user presses "send" in the `view`, I send the image from I the URL the I stored during the file upload event
```
say(
        channel=channel_id,
        blocks=[
            {
                "type": "image",
                "title": {
                    "type": "plain_text",
                    "text": 'some title,
                    "emoji": True
                },
                "image_url": <here I need the image URL from slack>,
                "alt_text": 'some text'
            }
        ]
   )
```

**Comment by filmaj** [comment]
Hi @ArturFortunato , got it. So you _are_ able to get a reference to the image, or you having trouble with that? Sorry, hard to piece together how the different event handlers / functions interoperate. I am assuming that your call to ` save_all_image_links()` in the file-share message event handler saves the link to some database, and then you retrieve it from that database when you need to open a view?

I am still kind of confused haha. Your original question implied this had something to do with image permissions, but now I am not sure that's the issue anymore. Happy to help - I just need to understand the situation better 😄

**Comment by ArturFortunato** [comment]
Hello @filmaj ! Yes, so
* When the file-share event fires, I save the URL of the image (all of the image URLs that the API shares).
* When a slash command opens, I need to show that image in a view
* When the view is submitted, I need to send the image to the chat

Both the view and sending the message fail using all Slack URLs. I talked about permissions because I receive an error saying "failed to download image" when trying to use it!

Seems like Bolt is trying to download it first, but it doesn't have permissions. How can I solve this?

Thanks 😄

**Comment by filmaj** [comment]
I see. Yes I think this situation could be complex, mainly because it depends on _who_ uploaded the file, that is: who the file owner is.

If you take a look at the file properties in your file-share event handler, you will find a property `public_url_shared`. If this is `False`, then the file (image) was uploaded by a user in such a way that they may not desire for the file to be publicly available. A requirement for the Block Kit image elements is that the URL for the image be publicly available. Combine that with the fact that by default, any [file uploaded to a Slack workspace requires authentication](https://api.slack.com/types/file#auth) to access, and you have a situation where likely the file/image you are trying to use in the modal is not actually publicly accessible. You can verify this by seeing what the response to `curl -v <image-url>` is (without any Authentication headers, or not loading in your browser, which may have authentication tidbits leftover via cookies or otherwise).

One workaround that _might_ work for you is to use the [`files.sharedPublicURL` API](https://api.slack.com/methods/files.sharedPublicURL). This explicitly sets an uploaded file to be public. However, if this file was not uploaded by your application, then your application would not be able to execute this API with its own bot token! If you can have your bot retrieve a user token on behalf of the user, that is, authenticate via OAuth on a per-user basis to ensure the user explicitly gives your app permission to make changes to files they upload, then you should be able to use this API. Check out the discussion in #611 to understand in more detail the steps needed to have your bot save individual user tokens (and what example we have in this repo to help guide you through this).

**Comment by ArturFortunato** [comment]
Hum, that really blocks what I'm trying to do. But:
* if I share an image to a channel
* right-click it and copy the link (this link is private)
* Paste it in a different channel

This works! Even if the user was not originally sent by me. Why does it work for that situation but not on my use case?

**Comment by seratch** [comment]
@ArturFortunato Sorry for the confusion here. 

Unfortunately, as of today, **no Block Kit component can display image data uploaded in your Slack workspace**. Meaning, image blocks/block elements can display **only publicly visible image URLs**. Thus, a simple answer to your original question is that, unfortunately, there is no workaround for it at this moment. 

We've already received this feedback many times and our product teams are aware of this need. However, we don't have anything to share about whether and when the enhancement to enable developers to display uploaded files in blocks.

The only workaround that I can share is to stop using blocks for the message plus to include the file URL in the top-level text property. With this, Slack renders the preview of the image file as an attachment for you.

**Comment by ArturFortunato** [comment]
Thank you for your explanation @seratch 😄 

Looking forward for this feature!
