### ISSUE TITLE
Why do I need to set a redirect URL to opt in to token rotation

### ISSUE THREAD

**Issue by christopherdavies-gel** [slackapi/bolt-python#746]
I'm currently trying to enable token rotation on my Slack bolt app using socket mode, but I have a question that I cannot find the answer to in any of the documentation.

In order to opt in to token rotation, it tells me I first have to add a redirect URL to my app, but what exactly does this URL do, and where should it point?

I have added a URL and turned on token rotation, and my app still appears to be working fine, but the URL I put in is totally made up and doesn't exist... so what exactly is the point of it? Want to make sure I am not missing something before I make the same change in our prod version

#### The `slack_bolt` version

```
slack-bolt==1.14.3
slack-sdk==3.18.3
slackclient==1.3.2
```

#### Python runtime version

3.10

**Comment by seratch** [comment]
Hi @christopherdavies-gel, thanks for asking the question, and we're sorry for your confusion with the document.

When you turn on token rotation for an app, the app has to be installed via Slack's OAuth flow, not the install button on your app admin page. This is because token rotation requires your app to manage the latest pair of an access token and its refresh token in a database. To enable this, your app's installations must go through the OAuth flow instead of generating a static access token from the admin page.

As for the expected Request URL, with bolt-python's default settings, the URL can be `https://{your public domain}/slack/oauth_redirect`. You can set this URL in the admin page. You don't need to pass the URL in your source code if you have only one Request URL. If you have multiple Request URLs (this can be useful for situations like providing multiple installation patterns with different sets of scopes), your code needs to pass one of them. Refer to bolt-python document and examples for details:
* https://slack.dev/bolt-python/concepts#authenticating-oauth
* https://slack.dev/python-slack-sdk/oauth/index.html
* https://github.com/slackapi/bolt-python/blob/main/examples/oauth_app_settings.py

Also, the default built-in implementation of `InstallationStore` is local file system-based. Going with this for production apps is not recommended. Please consider using any of the database-based one [here](https://github.com/slackapi/python-slack-sdk/tree/main/slack_sdk/oauth/installation_store) or implementing your own if the built-in ones are not suitable for your apps.

I hope this was helpful to you!

**Comment by christopherdavies-gel** [comment]
Thanks for getting back to me. So presumably in that case, I would actually need to reinstall the app in our slack to actually get it working?
