### ISSUE TITLE
How to send notification to another user's slack workspace 

### ISSUE THREAD

**Issue by dsharma522** [slackapi/bolt-python#756]
I want to send slack notification (message as an app to another workspace).

1. I have created a slack app as `slack_app`
2. I have installed `slack_app` into my own_workspace as `own_ws`.
3. A external users say `user_x` has installed my slack app into their workspace. 

I want to automate this sending notification business using third parties for example, using [courier](https://www.courier.com/blog/courier-live-sending-notifications-via-slack/) or using something else library.

I have webhook url of `user_x`'s slack workspace which i caught during oauth installation and that is something can be used to send messages but how to automate this sending notification via some third party.

How we can send notification/message into another workspace ? I did research a bit but could not find relevant information anywhere. 

Sorry that creating this an issue, It is Question/discussion label. I could not find anything, hence posted here for some positive response.

**Comment by hello-ashleyintech** [comment]
Hi, @dsharma522! Thanks for submitting your question! 🙌 

To best help with answering this question, I think I might need some more information here on the use case. Are you hoping to send messages through your app to all workspaces that have the app installed that contain updates / notifications regarding your app, or are you trying to accomplish something else?

**Comment by dsharma522** [comment]
1. Are you hoping to send messages through your app to all workspaces that have the app installed that contain updates / notifications regarding your app ? 

    Currently this is not the case which i need help with. But it would be great if I can get help with that as well as we can plan to send notifications regarding updates.


2. Are you hoping to only send it to certain users within the workspace or have these notifications publicly available across each workspace with the app installed ?

    Yes, I want these notifications publicly available for a targeted workspace for which we generated message/notification at the backend. This targeted workspace can be either of external user's who have installed the app or it can be the same workspace where I developed the app.

3. Or are you trying to accomplish something else? 
    I want to automate these sending notifications with some third party notifications service sender such as 
[courier](https://www.courier.com/blog/courier-live-sending-notifications-via-slack/) or any other third party.

**Comment by hello-ashleyintech** [comment]
Thanks for the clarification @dsharma522!

Based on my understanding of description here as well as reading over the Courier documentation, you could try the following approach:
* Since you would like your Slack app notifications to be public to everyone in the workspace, you can get your Slack app to create a public channel in every workspace that the app is installed to and have the app invited to that channel to be able to post messages.
* With OAuth, all installation instances and related info are stored in your installation datastore ([view implementation for the `installationDatastore` here](https://slack.dev/bolt-js/concepts#authenticating-oauth)), including bot tokens. You can use this data to pass to Courier. You can also see about storing the `channel_id` for your Slack app's notification channel in your Datastore instance in the entry corresponding to the installation to that specific workspace where the channel was created.
* Then, you can follow a guide for a third-party notification app such as Courier to create notifications and their templates and then use some sort of script to retrieve workspace data from the datastore, then run the API call to alert some (or all) workspaces that have the app installed with the specific notification you've created. To run the API call to Courier specifically, it looks like you'll need to pas in the `bot_token` and `channel_id` as highlighted [here](https://www.courier.com/docs/guides/providers/direct-message/slack/#sending-to-a-public-or-private-channel)
* In terms of automation, you can automate the running of the script described above and dynamically pass in templates for different notifications you'd like to send. You can also dynamically alert workspaces based on information queried from what is stored in the installation store.

Essentially, you will rely on your OAuth installation datastore here to keep all basic information for installations, and this also will be where you will actually get the installation information that is needed (such as a bot token) to send off. You can also use this to store other information, such as what workspaces should receive certain types of notifications. I hope this helps!

**Comment by dsharma522** [comment]
Thanks @hello-ashleyintech 
I do understand the above points but not very clear for 
> Then, you can follow a guide for a third-party notification app such as Courier to create notifications and their templates and then use some sort of script to retrieve workspace data from the datastore, then run the API call to alert some (or all) workspaces that have the app installed with the specific notification you've created. To run the API call to Courier specifically, it looks like you'll need to pas in the bot_token and channel_id as highlighted [here](https://www.courier.com/docs/guides/providers/direct-message/slack/#sending-to-a-public-or-private-channel)

I am not sure how third party will send notification to different workspace belongs to another user. I will try to find out more.

**Comment by hello-ashleyintech** [comment]
Sounds good! I got that last bit from reading through [these Courier docs](https://www.courier.com/docs/guides/providers/direct-message/slack/#sending-to-a-public-or-private-channel), so they might be helpful to learn more! It looks like on the Courier side, they will just need the bot token for the user's workspace as well as the channel you'd like to post in to be able to send a message notification.

I will close this issue out since it seems that the original question was addressed, but if you have any additional questions please feel free to submit a new issue!
