### ISSUE TITLE
Running app in shared channels results in Auth error

### ISSUE THREAD

**Issue by kafejo** [slackapi/bolt-python#767]
I have an app installed on clients workspace and they have the following workspace setup: 1 primary workspace with a shared channel where are people from 2 other workspaces. The app works just fine for the users in the primary workspace but for the other workspaces the behaviour is quite odd. 

- If a user on one of the secondary workspaces uses slash command, they receive `/<command>  is not a valid command.`
- If a user on one of the secondary workspaces taps on a button generated by the app in the channel, they are presented with a modal window, but when they try to submit that modal they receive an error. From our logs it's `ERROR:slack_bolt.MultiTeamsAuthorization:Although the app should be installed into this workspace, the AuthorizeResult (returned value from authorize) for it was not found.`

### Reproducible in:

I cannot reproduce it outside of client's workspace. 

#### The `slack_bolt` version

```
"slack-bolt": {
            "hashes": [
                "sha256:583a319734ee7de2fca758605c92253de7b3c9ef72d0c38251126c055af0d1c1",
                "sha256:8ead9331d7733a1ed364c4c57cf7a10fcb8c4be509ddba778c04e9efee9883cf"
            ],
            "index": "pypi",
            "version": "==1.15.1"
        },
"slack-sdk": {
            "hashes": [
                "sha256:5db78a3ed3c58b3b0a2bdbe40bac43c7b00edcbc12ff6a7778ac5cbe3a3a2899",
                "sha256:a0bafb9e53ffbc408a8b5a42443525aac2c0c7347223d9373dd9d41cf90c9343"
            ],
            "index": "pypi",
            "version": "==3.19.1"
        },
```

#### Python runtime version

Python: 3.10

#### OS info

Heroku

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by e-zim** [comment]
Hi @kafejo! If you're using user tokens in your requests, then this error may be happening if the users from the other workspace have not installed the app (and therefore don't have a user token). If this is the case, [the suggestions in this comment](https://github.com/slackapi/bolt-python/issues/723#issuecomment-1258755594) might help.

There's also a chance that these [multi-channel guests do not have permission to run slash commands or shortcuts](https://slack.com/help/articles/201259356-Slash-commands-in-Slack) in the primary workspace, which can be changed by the owner of the workspace from the "Configure apps" page under the "App Management Settings" section on the workspace settings page (your-workspace.slack.com/admin/settings).

However, I'm not sure if either of these are causing these auth errors since the channel guests can successfully open modals... I'd be interested in knowing the event types and tokens you are using if neither of the above resolves these errors!

**Comment by seratch** [comment]
To add to @e-zim's points, let me share a few more things:
* If all the workspaces are under the same Enterprise Grid organization, you can consider enabling org-wide installations for your app. With that, all the workspaces in the same org consistently work in the same way
  * https://api.slack.com/enterprise/apps
  * https://slack.dev/bolt-python/concepts#authenticating-oauth
* If the button behavior in a shared channel can arise, bolt-python can do better job to support the use case. I will look into it later on.

**Comment by kafejo** [comment]
Thanks for your feedback guys. It seems it's only happening on the enterprise grid. If I have 2 unrelated workspaces and I create a shared channel on the primary workspace where my app is installed, the users from the secondary workspace cannot actually use the slash command.

I checked the [multi-channel guests do not have permission to run slash commands or shortcuts](https://slack.com/help/articles/201259356-Slash-commands-in-Slack) and they are all disabled (all slash commands are allowed).

The enterprise grid settings are also allowed. 

What I find strange is the interaction with the app. In the example above the slash command doesn't work but the button actions work without a problem. On the enterprise grid neither seems to work.

Is there a way I could create my own enterprise grid for testing? I couldn't find any instructions around that.

**Comment by seratch** [comment]
>If I have 2 unrelated workspaces and I create a shared channel on the primary workspace where my app is installed, the users from the secondary workspace cannot actually use the slash command.

Yes, you are right and this is a behavior by design. If you desire to unlock the slash command to other workspaces, your app needs to be installed in other workspaces too via either org-wide or individual installation. In your case, I definitely recommend going with org-wide installations (the one I mentioned above). You can choose a few of the workspaces under your grid org if you want to limit the installations.

>What I find strange is the interaction with the app. In the example above the slash command doesn't work but the button actions work without a problem. On the enterprise grid neither seems to work.

Interactive components in a channel message and Events API event delivery such as app_mention, message, and reaction_added can work in a shared channel. Contrarily, slash commands, global shortcuts, and so on do not work in the same way. So, the situations that you are seeing is expected.

>Is there a way I could create my own enterprise grid for testing? I couldn't find any instructions around that.

Yes, there is. You can submit a request to create your grid sandbox for app development from here: https://api.slack.com/enterprise/grid/testing (click the sign up form link there)
