### ISSUE TITLE
AuthorizeResult not found when using file-based SQLite3 on Heroku

### ISSUE THREAD

**Issue by Guisch** [slackapi/bolt-python#805]
Hello

I created a slack bot with bolt-python. The bot is quite simple: it is listening to all messages and send Ephemeral when there's a regex match.
The bot is hosted on Heroku.
I use an SQLite store:
```python
# Set up Slack App
app = App(
    oauth_flow=OAuthFlow.sqlite3(
        database="./slackapp.db",
    ),
)
```

Issue: When I installed the bot with the `/slack/install` endpoint on our workspace, it works for few hours, then stop working and the following message kicks in at every events received:
```
Although the app should be installed into this workspace, the AuthorizeResult (returned value from authorize) for it was not found.
```
To fix it, I have to re-install the bot on the workspace.

Am I doing something wrong ? I was using filestore storage before and moved to SQLite thinking it would fix the issue but it did not.

Versions used:
```
slack-bolt==1.16.1
slack-sdk==3.19.5 #for SlackApiError
```

Let me know if you need more details. Thanks 🙏🏻

**Comment by seratch** [comment]
Hi @Guisch, thanks for asking the question!

>database="./slackapp.db",

The cause of your issue is that you're using the local file system-based InstallationStore. The local files in a Heroku instance can be flushed when the instance is shut down. Also, when you scale out the app with a few instances, the installation store does not work as expected.

Instead, you can use a production-grade database for storing the installation data. PostgreSQL can be a good option for Heroku apps. We offer a built-in SQLAlchemy-based installation store, too. The installation store can easily connect to your database: https://github.com/slackapi/bolt-python/blob/v1.16.1/examples/sqlalchemy/oauth_app.py#L17 

I hope this helps.

**Comment by Guisch** [comment]
Ok that make sense. Thanks a lot for the super fast answer 🙏🏻
