### ISSUE TITLE
Unclear emoji names for reactions

### ISSUE THREAD

**Issue by arvitus** [slackapi/bolt-python#808]
I'm trying to add reactions to a message using the `client.reaction_add()` method.
II use [this](https://gist.github.com/shello/efa2655e8a7bce52f273) random emoji generator. With this generator I get the emoji, it's Unicode value and it's name in a tuple. Since the `reaction_add()` takes the emoji name I give it to the method but I get a 'invalid_name' error.
I figured out that slack only accepts the names if they are in a certain format like underscores or dashes instead of spaces but it seems like there is no logic to it. Sometime the emoji names has underscores, sometimes dashes and sometimes both and sometimes it's even a completely different name than the Unicode one. The only emojis that reliably work are the ones with only one word as name.

So what's the best way to use random emojis for reactions? How should I format the names or is there a library that can do that for me?

(And why doesn't slack just accept the emojis but needs their name? But that's something for a different question.)

**Comment by eddyg** [comment]
Hi @arvitus.

Emoji "short names" (the part between the colons) are often used in systems instead of raw Unicode values.

The code you linked is using Python's built-in Unicode name converter, which, according [to the docs](https://docs.python.org/3/library/unicodedata.html) uses [this data](https://www.unicode.org/Public/14.0.0/ucd/NamesList.txt) for translation.

This data is much different than the standard Emoji data! For example, it lists `WIND BLOWING FACE`, not `wind_blowing_face`.

Although Python provides an "official" translation to the Unicode standard, I would recommend using a different way to lookup Emoji for use in Slack. A common reference used by many apps and websites that use human-facing emoji short-names (like GitHub) is available in the [emoji-data](https://github.com/iamcal/emoji-data) repo. For example, you can open this [table](http://projects.iamcal.com/emoji-data/table.htm) and look at the "short name" column and see all the names you're used to seeing in Slack. The end of the repo's README contains links to libraries that make utilizing this data easier.

Hope that helps.

**Comment by arvitus** [comment]
Thank you for the quick answer! The links you provided seem to be what I was looking for, thanks again.

**Comment by mwbrooks** [comment]
Thanks for the quick answer @eddyg ❤️ You're awesome!

@arvitus Thanks for reaching out and asking about the best approach to managing emoji names in Bolt Python. Hopefully the response helps other developers as well. Good luck with the app!
