### ISSUE TITLE
Pass ts from ack reply to lazy listener

### ISSUE THREAD

**Issue by asontha** [slackapi/bolt-python#810]
I think the ask is pretty straightforward. I want the ts from the ack in the lazy listener to be passed down to my long running function. Is there any way to make that happen? Right now, given that this is going to get deployed to lambda, I'm somewhat tempted to just assign it in the global variable scope and then re-access it in my long running method.

**Comment by seratch** [comment]
Hi @asontha, thanks for writing in! I understand your use case, but unfortunately, this is not feasible in a simple way. The `ack()` method does not have any response because it's an HTTP response under the hood.

To know the `ts` of a message posted by your `ack()` call, the only way I can share is to call [conversations.history API](https://api.slack.com/methods/conversations.history) to fetch the latest messages in the channel, and then find the one your app just posted.

I know the above approach may not be an easy solution, but I hope this was helpful to you. Let us know if you have more to ask on this :wave:

**Comment by seratch** [comment]
I've provided an answer to this question, so let me close this issue now. Please feel free to write in whenever you have further questions on this topic!
