### ISSUE TITLE
Trying to deploy to AWS Lambda - boto3 Module not found

### ISSUE THREAD

**Issue by asontha** [slackapi/bolt-python#811]
Trying to deploy on AWS Lambda so I switched from __init__ to `def handler` and started using `SlackRequestHandler`. Getting this Module not found error now.

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

slack-bolt==1.16.1
slack-sdk==3.19.5

#### Python runtime version

Python 3.10.9

#### OS info

ProductName:    macOS
ProductVersion: 12.5
BuildVersion:   21G72
Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000

**Comment by seratch** [comment]
Hi @asontha, the modules under `slack_bolt.adapter.aws_lambda` indeed depends on boto3, which is the official AWS SDK for Python apps. Also, since boto3 is an optional module for this Slack SDK, you need to install it when you run the code in non-AWS environments such as your local machine (when you run an app on AWS Lambda, boto3 is automatically installed). 

I hope this helps. Let us know if you have further questions on this.

**Comment by asontha** [comment]
Got it! Let's close this one for now.
