### ISSUE TITLE
Workflow marked legacy?

### ISSUE THREAD

**Issue by JoshuaLyle** [slackapi/bolt-python#814]
After reading the docs thoroughly, I can't understand why the workflow section is marked as Legacy. I'm looking to have several steps iteratively gather information from several different responses before taking some action and I don't see a way to do that with simple actions passing values to bolt besides building some type of data store locally. Workflows seemed to be the perfect fit as I can gather several inputs before taking an action on the final set of data but I don't want to build on something that is marked Legacy. I don't see a note on why it was marked Legacy or what the alternative would be so could someone explain why that section is marked so in the docs and if workflows are still a reasonable thing to use in to build new apps?

**Comment by seratch** [comment]
Hi @JoshuaLyle, thanks for writing in!

The section is marked as legacy because our next-generation platform feature (still in beta) will provide a better way to implement the same in the near future. Here are a few resources about the beta platform feature:

* https://slack.dev/bolt-python/future/concepts
* https://api.slack.com/future

The newer version of Workflow Builder is under development, so the next-gen platform does not provide the same functionality with the existing custom step feature yet. But, in the near future, your "function" in a next-gen platform app can work as a step in any workflow. You should probably be curious about the timeline for the next-gen's GA release, but sorry I cannot tell you the details now.

As for the existing "Steps from Apps" feature, it will be maintained for a certain period. However, with that being said, we encourage developers to consider the next-gen platform functions as the primary option for new app development.

I know that the current state of the next-gen platform may not be a good fit for your need today, but I hope my reply here is helpful to you.

**Comment by JoshuaLyle** [comment]
Thanks Kazuhiro!

This is great information and I appreciate the details in the response!

One thing I may suggest is to add a note or link to the intended replacement feature (or lack thereof) in a deprecation notice in the doc. Most cases I've seen in docs with legacy features mentions have a link to the stable version of the feature nearby. One other thing I find peculiar is that is was marked legacy before its replacement was out of beta. I would imagine they'd coexist as main features before deprecating the older legacy feature.

I hope this don't come off as criticism! This is an excellent library and I just hope to avoid any questions like mine in the future from others.
