### ISSUE TITLE
Tracking metrics with Prometheus

### ISSUE THREAD

**Issue by asontha** [slackapi/bolt-python#820]
Hello! We're about to install the Slack bot in a client's workspace, but we need to track metrics as we won't have the ability to join their workspace and see how the bot is being used. Is there an example on how to use the Bolt API with the Prometheus python SDK?

https://github.com/prometheus/client_python

**Comment by seratch** [comment]
Hi @asontha, I've never used Prometheus' Python client, but at a glance, their README is so detailed that you can go with any of the solutions there. 

If I were a developer to enable it for a Python web app, I may consider going with their Flask middleware solution: https://github.com/prometheus/client_python#flask With that, you can reuse our Flask example code (https://github.com/slackapi/bolt-python/tree/main/examples/flask) as-is.

One thing that I wanted to mention is that, if you're planning to go with Socket Mode for the production app, perhaps there is no simple solution on the Prometheus project side. You need to write your own code to track the numbers of metrics such as requests, response time, and so on.

I hope the above helps you! Since we are not maintainers of the Prometheus project, we are unable to help you out further on this. Would you mind if I close this issue?

**Comment by asontha** [comment]
Sounds good! You were right, I was able to get it integrated fairly easily :)
