### ISSUE TITLE
Upload files functionality in Modals 

### ISSUE THREAD

**Issue by sharvesh06** [slackapi/bolt-python#821]
There is no way to upload a file using Modal in the slack app, can we add a new component to upload file using the Modals

### Category (place an `x` in each of the `[ ]`)

* [x ] **slack_bolt.App** and/or its core components
* [x ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [ ] Adapters in **slack_bolt.adapter**
* [ ] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by WilliamBergamin** [comment]
Hi @sharvesh06 thanks for requesting this feature 💯 

Unfortunately your feature request addresses the capabilities of the [Slack Web API](https://api.slack.com/methods), not just `bolt-python`.
I've submitted your request through our internal channels where it will be discussed!

I will close this issue since it does not pertain directly to `bolt-python`
Hopefully your request becomes a feature 🙏
