### ISSUE TITLE
OAuth Flow Install through Slack Bolt Python Error

### ISSUE THREAD

**Issue by ejwinter-amazon** [slackapi/bolt-python#857]
Hello, 

I am using Slack Bolt in python to create a slack app. I have token rotation on and need to install the app. I have the app redirect url pointed to: ENDPOINT/slack/install. I also enabled the oauth setting in the App initialization. (See below.) 

### Reproducible in:

```python
app = App(
    process_before_response=True,
    request_verification_enabled=True,
    signing_secret=secrets_client.get_secret("Signing Secret"),
    token=secrets_client.get_secret("Bot Token"),
    token_verification_enabled=True,
    oauth_settings=OAuthSettings(
        client_id=secrets_client.get_secret("Client ID"),
        client_secret=secrets_client.get_secret("Client Secret"),
        scopes=[
            "app_mentions:read",
            "chat:write",
            "commands",
            "emoji:read",
            "files:write",
            "groups:history",
            "im:history",
            "im:read",
            "im:write",
            "mpim:write",
            "reactions:read",
            "reactions:write",
            "files:read"
        ],
        user_scopes=[],
        install_page_rendering_enabled=False,
    )
)
```

#### The `slack_bolt` version

slack-bolt==1.14.3
slack-sdk==3.18.1

#### Python runtime version

Python 3.8.16

#### OS info

AWS Python Lambda  - x86_64

#### Steps to reproduce:

1. Use App code above in AWS Lambda tied to an AWS API Gateway. 
2. Create GET and POST requests to API Gateway for ENDPOINT/slack/install
3. Try and install the app in your workspace.

### Expected result:
The app to be installed on my workspace.

### Actual result:

![Screen Shot 2023-03-13 at 13 00 35](https://user-images.githubusercontent.com/127776962/224772845-53a58b54-ac96-44fd-999d-d2b9176cc79a.png)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hi @ejwinter-amazon 👋🏻 Thanks for the detailed error report!

I don't see the immediate answer to your question, but I'd like to make a few suggestions for you to check while other teammates are able to look at the issue 👀 

The `invalid_browser` error is produced by the Bolt Python framework and can occur when the installation was not started from `/slack/install`. You can learn a little more in https://github.com/slackapi/bolt-python/issues/857 and from this [code sample that generates the unique state](https://slack.dev/python-slack-sdk/oauth/). It looks like you're using the URL, but I wanted to mention this in case it helps.

Since you're using AWS Lambda, you may also want to double-check that your app is using the [Lambda Adapter and (possibly) Lambda OAuth Adapter](https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/aws_lambda_oauth.py). From your code sample, I can see that you're enabling `process_before_response` but I wanted to ensure that you're also using the Lambda Adapter.

**Comment by ejwinter-amazon** [comment]
Hi @mwbrooks,

Thanks for the response! I have updated the code to below and am getting the same error.

```
app = App(
    process_before_response=True,
    request_verification_enabled=True,
    signing_secret="SECRET",
    token="TOKEN",
    # disable token verification to avoid sending requests to slack during build
    token_verification_enabled=True,
    oauth_flow=LambdaS3OAuthFlow(
        settings=OAuthSettings(
            client_id="ID",
            client_secret="SECRET",
            scopes=[
                "app_mentions:read",
                "chat:write",
                "commands",
                "emoji:read",
                "files:write",
                "groups:history",
                "im:history",
                "im:read",
                "im:write",
                "mpim:write",
                "reactions:read",
                "reactions:write",
                "files:read"
            ],
            install_page_rendering_enabled=False,
            #state_validation_enabled=False,
            install_path="/",
        ),
        oauth_state_bucket_name='BUCKET1',
        installation_bucket_name='BUCKET2'
    ),
)
```

I have found that uncommenting the state_validation_enabled field makes everything work. However, I dislike the fact that I have to disable a validation test to make things work. So I'm looking for a better solution.

**Comment by WilliamBergamin** [comment]
Hi @ejwinter-amazon

Thanks for this detailed investigation, what happens if you set `install_page_rendering_enabled=True` instead of `False` or if you try to change the default `state_cookie_name` to example `python-slack-app-oauth-state` the default is `slack-app-oauth-state`
