### ISSUE TITLE
Have a documentation regrading testings bolt applications

### ISSUE THREAD

**Issue by yuvalshi0** [slackapi/bolt-python#859]
I'm developing a slack bot using bolt, and I wanted to write some tests for it, but there is no documentation regarding testing, in the end, I look into your test and found [this](https://github.com/slackapi/bolt-python/blob/v1.6.1/tests/scenario_tests/test_block_actions.py#L154-L189) piece of code, but I ough to think there should be a dedicated section about it

**Comment by mwbrooks** [comment]
Hey @yuvalshi0 👋🏻 We totally agree that it needs to be easier to test Bolt apps both from a unit test and end-to-end test perspective!

Issue https://github.com/slackapi/bolt-python/issues/380 is currently tracking this feature request. You may want to take a look at the conversation for a few more recommendations on how to get started testing (and share your own suggestions!). At the moment, this work is slated for the 2.x release of Bolt Python, although it may be delivered sooner.

Since we have an open issue for testing documentation, I'm going to close this issue. I highly recommend that you join the conversation in #380, leave a reaction to the main issue and leave a comment that this is important to you. It'll help add more weight to prioritizing it!
