### ISSUE TITLE
OAuth Redirect failing

### ISSUE THREAD

**Issue by asontha** [slackapi/bolt-python#867]
#### The `slack_bolt` version

slack-bolt==1.16.1
slack-sdk==3.19.5

#### Python runtime version

Python 3.10.9

#### OS info

ProductName:    macOS
ProductVersion: 12.5
BuildVersion:   21G72
Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000

#### Steps to reproduce:

1. Install our Slack bot: https://kyber-slack-bot.fly.dev/slack/install
2. Hit add to Slack button
3. Authorize to be added
4. "Oops something went wrong"

### Expected result:

Slack bot should simply get installed

### Actual result:

User result:
![image](https://user-images.githubusercontent.com/67022327/225993167-5a28ab31-0509-497a-a704-cc57fa2a0840.png)

Logs result:
![image](https://user-images.githubusercontent.com/67022327/225993275-fecdb12f-9393-42a1-9ac7-34b84df86c56.png)

**Comment by asontha** [comment]
We've been able to install this on multiple workspaces already. Typically, we'll hit this once and then it works once the user hits "here". However, this time, no matter how many times we retried, it kept failing and returning to this same page.

**Comment by seratch** [comment]
Hi @asontha, thanks for asking the question! but with given information, we may not be able to help you out. Please check your server-side logs to see what's happening in the scenario. 

Generally speaking, when the error comes up, the installing user should be visiting the same oauth_redirect URL twice or more times, and/or your server-side might lose the persisted "state" data on the server-side for some reason. The cause is that state parameter in the query string no longer exists on the server-side. Here is the relevant code in bolt-python:

* https://github.com/slackapi/bolt-python/blob/v1.16.4/slack_bolt/oauth/internals.py#L138-L139
* https://github.com/slackapi/bolt-python/blob/v1.16.4/slack_bolt/oauth/oauth_flow.py#L242-L252

What kind of `state_store` do you use? You need to use a unified datastore for it instead of the default local file system based one, which is useful only for local development or a simple app that runs on a single host. If you're using the file system one, please switch to any of the available options [here](https://github.com/slackapi/python-slack-sdk/tree/main/slack_sdk/oauth/state_store) or your own one.

I hope this helps.

**Comment by asontha** [comment]
Here are all of the server side logs from when we attempted the install multiple times
![image](https://user-images.githubusercontent.com/67022327/226065426-bcc9fe03-de63-4cbd-a195-d2eab6695de4.png)

We're using S3 for our state store and for all other installations it worked just fine. We're currently installed in 5 or so workspaces already.

**Comment by asontha** [comment]
Here's how we have our OAuth state store configured:

```
s3_client = boto3.client(
    's3',
    aws_access_key_id=os.getenv('AWS_S3_ACCESS_KEY'),
    aws_secret_access_key=os.getenv('AWS_S3_SECRET')
)

s3_installation_store = AmazonS3InstallationStore(
    s3_client=s3_client,
    bucket_name=os.getenv('AWS_S3_BUCKET'),
    client_id=os.getenv("SLACK_CLIENT_ID"),
)

s3_state_store = AmazonS3OAuthStateStore(
  s3_client=s3_client,
  bucket_name=os.getenv('AWS_S3_BUCKET'),
  expiration_seconds=10
)

oauth_settings = OAuthSettings(
    client_id=os.getenv("SLACK_CLIENT_ID"),
    client_secret=os.getenv("SLACK_CLIENT_SECRET"),
    scopes=["app_mentions:read", "chat:write", "chat:write.public", "commands"],
    installation_store=s3_installation_store,
    state_store=s3_state_store
)

## Initialize app
app = App(
  token=os.getenv("SLACK_BOT_TOKEN"),
  signing_secret=os.environ.get("SLACK_SIGNING_SECRET"),
  oauth_settings=oauth_settings
)
```

**Comment by seratch** [comment]
@asontha Can you adjust this durection? >expiration_seconds=10

10 seconds from the access to `/slack/install` could be too short. 5 minutes or so should be safe enough for security.

**Comment by asontha** [comment]
That fixed it! Thanks!
