### ISSUE TITLE
Getting 401 for GitHub webhook event to Slack Bolt Flask server

### ISSUE THREAD

**Issue by r-ramaraja** [slackapi/bolt-python#874]
When a user stars a GitHub repository, I want to receive the details of the event via a webhook and store the details in a DB and then send a Slack message.  
I have set up the GitHub webhook, and it works fine.  
I am using Python Slack Bolt and Flask to handle incoming webhook events and interact with Slack. Here's the code,

```python
import os
from flask import Flask, request
from slack_bolt import App
from slack_bolt.adapter.flask import SlackRequestHandler

app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)

flask_app = Flask(__name__)
handler = SlackRequestHandler(app)


@flask_app.route("/github/hook", methods=["POST"])
def handle_github_hook():
    print(request.json)
    # Store the details to the database
    # Send a message to the slack channel
    return 200


@flask_app.route("/", methods=["POST"])
def handle_challenge():
    return handler.handle(request)


@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    return handler.handle(request)

```
And I run it using `FLASK_APP=app.py FLASK_ENV=development flask run -p 3000`

When I star the repository, the webhook gets triggered as expected, and I can see it reaching the Flask server, but it fails with 401. The 401 error is at the point where GitHub sends a POST request to the Flask Server, and the Flask server responds with 401. How do I solve the Unauthorized error?
```
FLASK_APP=test.py FLASK_DEBUG=true flask run -p 3000
 * Serving Flask app 'app.py'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:3000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 133-509-728
127.0.0.1 - - [31/Mar/2023 15:53:22] "POST / HTTP/1.1" 401 -
```

#### The `slack_bolt` version

slack-bolt==1.17.0
slack-sdk==3.20.2

#### Python runtime version

Python 3.9.12

#### OS info

ProductName:            macOS
ProductVersion:         13.1
BuildVersion:           22C65
Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000

**Comment by seratch** [comment]
Hi @r-ramaraja, thanks for asking the question. 

The `handler.handle(request)` part can handle only incoming requests from Slack API server and Slack OAuth requests from web browser. So, if you need to receive a different type of request at `/` endpoint, your code need to be different. Meaning that, instead of using `handler.handle(request)` in the method, you can write your own code to handle a request. 

If you, otherwise, want to handle Slack requests at the `/` endpoint, plase make sure you've set a valid SLACK_SIGNING_SECRET string value for the app. The error is usually due to the misconfiguration of the value.

Does this make sense to you?

**Comment by r-ramaraja** [comment]
@seratch Thanks for the prompt response.
It makes sense now. I got it working. :)
