### ISSUE TITLE
How do i create a posts(long form content) as a response

### ISSUE THREAD

**Issue by Smyja** [slackapi/bolt-python#877]
On the slack web app, you can create a long form content by using the slack shortcut for create a post. I would like to respond to messages as a post(somewhat like a blog content with image links unfurled), how do i do that?

**Comment by misscoded** [comment]
Hi @Smyja! I'm not sure I follow, so bear with me:

> On the slack web app, you can create a long form content by using the slack shortcut for create a post

Can you provide a screenshot of what you're referring to, and the end state of what you'd like to accomplish?

**Comment by Smyja** [comment]
> Hi @Smyja! I'm not sure I follow, so bear with me:
> 
> > On the slack web app, you can create a long form content by using the slack shortcut for create a post
> 
> Can you provide a screenshot of what you're referring to, and the end state of what you'd like to accomplish?

This is what i am trying to create.
![slackpost](https://user-images.githubusercontent.com/20070770/230444376-17424904-a441-411d-9c02-30d9b764c946.png)

**Comment by seratch** [comment]
Hi @Smyja, unfortunately, creating a post from a 3rd party app is not supported and we don't have plans to enhance the platform to add it. A workaround that I can suggest is to create a text file and upload it using `files_upload` / `files_upload_v2` API method.

This may not be a great answer for you, but I hope this helps clarify things. Let us know if you have anything else to ask on this topic. Otherwise, would you mind closing this issue?
