### ISSUE TITLE
Codecov CI job for this project hangs

### ISSUE THREAD

**Issue by seratch** [slackapi/bolt-python#892]
Starting this month, the codecov CI job never succeeds. I am still unsure about the root cause of it but it seems that GitHub Actions runtime is unable to complete all the tests for some reason. Example: https://github.com/slackapi/bolt-python/actions/runs/4805729060/jobs/8552434332

Since unit test execution job is still working, let me disable the codecov job for now. We will look into it later.

**Comment by vgnshiyer** [comment]
Hello @seratch.. I took a look into this issue. By enabling debug traces in pytest and running test_async_aiohttp.py, I found that at line 32 is failing with the below error. (attached screenshot below)

<img width="592" alt="Screenshot 2023-06-14 at 3 30 43 PM" src="https://github.com/slackapi/bolt-python/assets/39982819/d013bf08-19dd-4a48-af35-a5c53b6be389">

It seems like asyncio is trying to get an event loop from some other thread instead of the Main thread. This however, only happens when we try to run multiple tests together (hence, in the CI).
Ref: https://techoverflow.net/2020/10/01/how-to-fix-python-asyncio-runtimeerror-there-is-no-current-event-loop-in-thread/

Replacing line 32 with something like this fixes the issue.
```
try:
    loop = asyncio.get_event_loop()
except RuntimeError as ex:
    if "There is no current event loop in thread" in str(ex):
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
```

Or maybe we can try having a static method named create_or_get_event_loop() since there are multiple files using this.

**Comment by seratch** [comment]
Hi @vgnshiyer, thanks for your comment! We are aware of the intermittent failure when running the tests for Socket Mode. The code can be improved for more stability.

The CI issue we track here is specifically related to test execution with Codecov (a process that involves collecting code coverage data and sending it to Codecov). The execution time is significantly longer when running tests with Codecov, compared to running the tests without it. Did you identify the runtime error you mentioned is causing the hanging (I mean not just intermittent failure)? I'm still uncertain about the connection here.

**Comment by vgnshiyer** [comment]
Yes. You must notice that the Codecov job always stops at this particular file test_async_aiohttp.py which I tried executing locally with a debug `--pdb` flag and that is when I discovered that it is this runtime error causing it.

**Comment by seratch** [comment]
Thanks for clarifying this! If you're happy to send a PR and sign our CLA, I'd love to have your contribution on this 👋 Otherwise, I will look into it later.

**Comment by vgnshiyer** [comment]
Thanks @seratch. Glad to know. I would like to contribute a PR on this.
