### ISSUE TITLE
Fastapi adapter not registering incoming requests from Slack

### ISSUE THREAD

**Issue by FayZ676** [slackapi/bolt-python#897]
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version
slack-bolt==1.18.0
slack-sdk==3.21.3

#### Python runtime version
Python 3.10.11

#### OS info
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))
## Code: app.py
```
from slack_bolt import App
from slack_bolt.adapter.fastapi import SlackRequestHandler

from dotenv import load_dotenv
import os

load_dotenv()

slack_bot_token = os.environ.get("SLACK_BOT_TOKEN")
slack_signing_secret = os.environ.get("SLACK_SIGNING_SECRET")

app = App()
app_handler = SlackRequestHandler(app)

@app.event("app_mention")
def handle_app_mentions(body, say, logger):
    logger.info(body)
    say("What's up?")

@app.event("message")
def handle_message():
    pass

from fastapi import FastAPI, Request

api = FastAPI()


@api.post("/slack/events")
async def endpoint(req: Request):
    return await app_handler.handle(req)
```

## Command to run
`uvicorn app:api --reload --port 3000`

## Output:
```
INFO:     Will watch for changes in these directories: ['/home/faizi/Projects/slack']
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     Started reloader process [13903] using StatReload
INFO:     Started server process [13905]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

### Expected result:
I expect the application to print "What's up?" in slack when I make a mention.

### Actual result:
No output from the slack app when executing a mention event inside of slack.
![Screenshot from 2023-05-04 11-17-37](https://user-images.githubusercontent.com/94952795/236293601-6cb8a51c-4e3e-4b81-8f8a-c314d56f6bb5.png)

![Screenshot from 2023-05-04 11-18-01](https://user-images.githubusercontent.com/94952795/236293569-54463667-4e2e-4730-9a71-90ba69a8b0c9.png)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by e-zim** [comment]
👋 Hey @FayZ676! It looks like your app is running over HTTP, which means you'll have to configure a Request URL after enabling events to receive notifications for subscribed events.

Could you check that you've toggled events "on" and that you've subscribed to the `app_mention` event, as well as added the `app_mentions:read` scope to your app? This can be checked on the "Event Subscriptions" and "OAuth & Permissions" pages respectively for [your app](https://api.slack.com/apps).

Since you're using a localhost to serve these requests, you might also consider using a tool such as [ngrok](https://ngrok.com/) to create a tunnel between your computer and the web for your Request URL. This will allow you to listen for and respond to events directly from your computer! Running `ngrok http 3000` will provide a forwarding URL that you can use for receiving events on by appending `/slack/events`. For example, `https://example.ngrok.app/slack/events`.

Hopefully some combination of these steps will bring the "What's up?" message to your channel, but if it doesn't feel free to let me know! Happy to explore this more if needed!
