### ISSUE TITLE
I got `This message contains interactive elements.` even though there were no interactive elements on message.

### ISSUE THREAD

**Issue by 0417taehyun** [slackapi/bolt-python#926]
#### The `slack_bolt` version

- Slack-bolt 1.16.1

#### Python runtime version

- Python 3.11

#### Circumstance

Hi, I edited users' message to add secondary message attachments via Bolt app by handling the events. However, the real user's message was changed to `This message contains interactive elements.` even though there were no interactive elements on message. I used this app for couple of months, and this is the first time to face this situation. It only happened when user sent message with image files.

The below message is a simple version of that case.

```JSON
{
   "type":"message",
   "text":"This message contains interactive elements.",  # This is the part that I did not expect. I intend to keep its original message.
   "files":[
     # ... Image file section
   ],
   "upload":false,
   "user":"...",
   "display_as_bot":false,
   "ts":"...",
   "blocks":[
      {
         "type":"rich_text",
         "block_id":"qPSoc",
         "elements":[
            {
               "type":"rich_text_section",
               "elements":[
                  {
                     "type":"text",
                     "text":"This message contains interactive elements."
                  }
               ]
            }
         ]
      }
   ],
   "edited":{
      "user":"...",
      "ts":"..."
   },
   "client_msg_id":"...",
   "attachments":[
      {
         "id":1,
         "blocks":[
            {
               "type":"rich_text",
               "block_id":"rdh",
               "elements":[
                  {
                     "type":"rich_text_section",
                     "elements":[
                        {
                           "type":"text",
                           "text":"Attachment message"
                        },
                        {
                           "type":"emoji",
                           "name":"smile",
                           "unicode":"1f604"
                        }
                     ]
                  }
               ]
            }
         ],
         "fallback":"[no preview available]"
      }
   ],
}
```

**Comment by seratch** [comment]
Hi @0417taehyun, thanks for reaching out!

The text "This message contains interactive elements" can indeed be confusing. This issue seems to be related to how Slack clients (desktop, iOS, Android) handle file upload scenarios, and not due to API calls by the Slack-bolt library. 

For inquiries such as this, our customer support team would be more able to assist. I'm sorry for the inconvenience, but we would appreciate it if you could contact our support agents either through /feedback in your Slack workspace or via https://my.slack.com/help/requests/new. It would be greatly appreciated if you could understand this.
