### ISSUE TITLE
Update a block message

### ISSUE THREAD

**Issue by suavelad** [slackapi/bolt-python#931]
I am trying to send a message to  3 users same time which contains a block and when one person responds to the  block, I intend to update the block message to. the other users.

I have tried using :

```python
client = WebClient(token=SLACK_TOKEN)
client.chat_update(
    channel=slack_user, ts=body["message"]["ts"], blocks=block
) # update message with block alterations
```

What is the best way to attend to this.

**Comment by zimeg** [comment]
Hi @suavelad 👋 The update method you shared seems like it will correctly update a message that received a block action event, so I am curious about your use case. Are you hoping to update multiple messages, each one sent to a different user?

If so, information about where and when these messages are being sent will somehow have to be retrieved for the update. I could imagine this being stored in a database for easy lookups or possibly by using [message metadata](https://api.slack.com/metadata/using) to store which users are receiving the message and `conversations.history` to find the `ts` of messages that need updating.

I hope this is helpful but please feel free to share any additional details around your use case or questions you might have!

**Comment by suavelad** [comment]
Hi @zimeg ,
Can I use the slack user id in the channel field , with. the ts of the original message for each user ?

**Comment by zimeg** [comment]
Apologies for the oversight, but if these messages are being sent to users directly (using a user ID in `chat.postMessage`) then the `channel` field for `chat.update` should be the conversation ID between the user and your app, not the user ID itself.

The response from `chat.postMessage` will return this conversation ID in the `channel` field as an ID beginning with `D` – e.g. `D058E75TASH`. With this and the `ts` also returned, you can individually update the original messages.

Since conversation IDs might be unknown at the time of sending the initial message, I now think using a database to store this information might be a preferable option. Updating message metadata with the received conversation IDs and message timestamps after posting all of the original messages still seems doable, but might be a more complicated approach.
