### ISSUE TITLE
Need to give client.post_message provided message in the thread created by the message from default "Send a message to" option in workflow builder

### ISSUE THREAD

**Issue by PrajwalNaik07** [slackapi/bolt-python#937]
I have created a workflow step which gives a response using client.post_message but this message should be a part of the thread of a message given by the workflow builder using "Send a message to" option, when I checked the document we can reply by getting thread ts, but unable to find a way to get thread ts of the first message sent using "Send a message to", to my workflow step. How to proceed

**Comment by seratch** [comment]
Hi @PrajwalNaik07, thank you for reaching out. Unfortunately, the current version of Workflow Builder doesn't support passing a posted message's 'ts' via workflow step variables.

As you may be aware, Slack is currently rolling out its next-generation Workflow Builder. This new developer platform does support your use case: https://api.slack.com/reference/functions/send_message However, it does not support bolt-python; you would need to write TypeScript code that runs on the Deno runtime. Despite this, the next-generation platform offers substantial improvements. We encourage you to explore this new platform for building your workflows.

If you have any questions about the new platform, please don't hesitate to post them on the new generation platform's SDK projec's issue tracker: https://github.com/slackapi/deno-slack-sdk/issues

Since there's no more information to share regarding this topic at the moment, we will close this issue. We appreciate your understanding, and we hope that you will find the new workflow platform beneficial.
