### ISSUE TITLE
Slow async authorize + middleware leading to operation_timeout even with lazy listeners

### ISSUE THREAD

**Issue by Leoputera2407** [slackapi/bolt-python#947]
I want to remove the `operation_timeout` on a slack command for my slack app. I have implemented lazy loading, however my middleware and authorize (installation store) can be slow sometimes, leading to `operation_timeout` message even when the command ran successfully i.e a modal was summoned.

#### The `slack_bolt` version
slack-bolt==1.18.0
slack-sdk==3.21.3

#### Python runtime version
Python 3.11.3

#### OS info
ProductName:    macOS
ProductVersion: 11.6.8
BuildVersion:   20G730

#### Steps to reproduce:
```python
slack_app = AsyncApp(
    oauth_settings=AsyncOAuthSettings(
        client_id=SLACK_CLIENT_ID,
        client_secret=SLACK_CLIENT_SECRET,
        scopes=SLACK_APP_PERMISSIONS,
        user_scopes=SLACK_USER_SCOPES,
        install_page_rendering_enabled=True,
        install_path="/slack/install",
        redirect_uri_path="/slack/oauth_redirect",
        installation_store=AsyncSQLAlchemyInstallationStore(
            client_id=SLACK_CLIENT_ID,
            logger=logger,
        ),
        state_store=AsyncSQLAlchemyOAuthStateStore(
            expiration_seconds=120,
            logger=logger,
        ),
        logger=logger,
    ),
    process_before_response=True,
)

async def just_ack(ack: AsyncAck):
    await ack()


def register_listeners(slack_app: AsyncApp):
    slack_app.command("/command")(ack=just_ack, lazy=[handle_command])


@slack_app.middleware
def some_heavy_middleware():
      slow_db_query()
```

I have a slack app that stores installation in SQLAlchemy. Intermittently, I got `operation_timeout` error, even though the app ran. I put some log statements and saw that the `async_authorize` and `middle_ware` must run before the just_ack is called.

However, sometimes the installation_store db query + middleware took more than 3s in wall time to get through. 

I was wondering if there's a way to ack even before the `just_ack`

I've tried to ack in before_authorize (as seen below) and ack in middleware
Sample code for before_authorize
```python
async def before_authorize(
      ack: AsyncAck,
          next_: Callable[[], Awaitable[None]],

):
   await ack()
   next_()


slack_app = AsyncApp(
        ....,
       before_authorize=before_authorize
)
```
And middleware
```python
@slack_app.middleware
def some_heavy_middleware(acl: AsncAck):
       await ack()
      slow_db_query()
```
However, I'm still getting the `operation_timeout` issue. Is there any way to go about it? 

    
### Expected result:
No, `operation_timeout` error message. The command run I.e. a modal was summoned, but the operation_timeout came out in the background.

### Actual result:
`operation_timeout` message came out even when the modal showed up.

**Comment by seratch** [comment]
Hi @Leoputera2407, thanks for the question!

1. **Improving `ack()` Performance:** If you want to improve the performance of your app's `ack()` response, consider bypassing the `some_heavy_middleware` for the `ack()` handling pattern. Specifically, the [`request.lazy_function_name` property](https://slack.dev/bolt-python/api-docs/slack_bolt/request/async_request.html#slack_bolt.request.async_request.AsyncBoltRequest.lazy_function_name) exists only when a request is intended for lazy listener execution. You can have an if/else condition within the global middleware to bypass certain executions, resulting in a faster `ack()` response. If it's necessary to execute the middleware for both ack and lazy, then it's worth optimizing the middleware method performance.

2. **`authorize` Function:** Regarding the authorize function, Bolt is designed to execute this function for every incoming request, ensuring necessary data is passed to middleware/listeners. To improve the method's performance, you might want to look into optimizing your database query, which is a common bottleneck.

I hope this helps.

**Comment by seratch** [comment]
@Leoputera2407 I see that you might be using the example code for `AsyncSQLAlchemyInstallationStore ` available [here](https://github.com/slackapi/bolt-python/blob/v1.18.0/examples/sqlalchemy/async_oauth_app.py#L26-L100). If that's the case, tweaking the database connection settings for the underlying "databases" library as outlined [here](https://www.encode.io/databases/connections_and_transactions/) could improve your app's stability. Since we're not maintainers of the databases library, we can't offer further specific advice on this front.

If you find debugging an asyncio-based app and database library challenging, you might consider switching to regular Python code coupled with the more stable SQLAlchemy library (meaning directly using SQLAlchemy with asyncio wiring). In general, troubleshooting for asyncio-based applications can be complex (even for the developers who are already faimilar with it), and if you don't have a compelling reason to continue using it, opting for a synchronous approach may be a practical choice.

I hope this guidance helps you either resolve the issue or consider an alternative approach that suits your needs. Thanks!
