### ISSUE TITLE
My command is now showing dispatch_failed

### ISSUE THREAD

**Issue by suavelad** [slackapi/bolt-python#951]
My command just started showing dispatch_failed error

/onboard failed with the error "dispatch_failed"

It shows across all the bot I have  and the API is not getting called (no logs from my end)
Please what could be the cause ?

**Comment by suavelad** [comment]
I tried using the url to test  but I got 'There is a glitch error'  but I am getting an error across all my slack apps  that has commands

 https://api.slack.com/apps/A04T4F7M77Z/onboard 
https://api.slack.com/apps/A059VGUMQLD/onboard

**Comment by zimeg** [comment]
Hi @suavelad! :wave: The `dispatch_failed` usually occurs when your app doesn't respond to a slash command and might be caused by a misconfigured URL. This also might be why no logs are being received by your bot.

Visiting the `https://api.slack.com/apps/.../onboard` URLs directly will expectedly error with 'There is a glitch' – our 404 page – since these pages are for app configuration itself. I don't think there's a way to test these commands using URLs like so, but these can instead be checked by calling a slash command in a workspace and watching the logs.

If you're using request URLs, could you check that each slash command has the correct request URL configured by going to **Features > Slash Commands > Edit icon**? Alternatively, Socket Mode should handle this configuration automatically.

Please let me know if the `dispatch_failed` error isn't solved by either case! It seems like your app has configured these correctly, so I am thinking this error is caused by an unexpected request URL.

**Comment by zimeg** [comment]
Glad to hear Socket Mode is working for you!

The `.start()` on your SocketModeHandler is a blocking call and might be preventing the rest of your API from handling other requests. Replacing this with [`.connect()`](https://github.com/slackapi/bolt-python/blob/2bec768b6ebf2002dd7ec269ef95dc850725648c/slack_bolt/adapter/socket_mode/base_handler.py#L29) might allow other your Django app to handle requests while your Slack app is still running.

Mixing Socket Mode with HTTP requests might be strange though, so if this doesn't seem to work I would check out [the Django integration example](https://github.com/slackapi/bolt-python/tree/main/examples/django) for a way to run a Django server with Slack app listeners. 

Please feel free to follow up if neither of these examples are suitable for your use case though!

**Comment by suavelad** [comment]
Hi @zimeg 

It works but however I noticed the following:

==> I have 3 bot apps : one for dev, staging and prod
         when I ran the app.command on prod using socket mode, it was the dev bot that responded. Please what could be the cause?

==> Secondly, my prod app is under review by your team, I will lik to generate an app token to aid my socket mode in production but it not available due to the on going app submission review. Please how can I generate the app token in production while it is still in review?

==> On the http request mode, after I deleted the slash command and recreated it severally, it worked  for the dev bot app.
       but staging and production is not working . Just showing the dispatch error

**Comment by seratch** [comment]
@suavelad Perhaps all the dev/staging/prod apps have the same name slash command, right? If that's the case, only the most recently installed one works in a workspace. Refer to the document for details: https://api.slack.com/interactivity/slash-commands#naming_your_command

As for the review-related question, going with Socket Mode is not allowed for publicly listed apps on the App Directory. Thus, as long as you plan to publish it there, Socket Mode is not available for it. That being said, you can still use Socket Mode for dev and staging apps without any issues. If my understanding of this is outdated, please ask the question directly to the review team. You can reply to the email you've received from them.

I hope this helps.

**Comment by suavelad** [comment]
Hi @seratch ,

Thanks for the clearification.
How can I fix  the dispatch error I am getting with the HTTP request mode  when I use the command.

It suddenly started working in my dev bot app but it just showing dispatch error for the other app.

No error on my backend console

**Comment by seratch** [comment]
In this case, your "dev" app overwrites other slash commands (check the above link to learn the reason). That's why other apps' commands do not reach to your app servers. I'd suggest naming those commands with a suffix, such as /my-command-dev for dev and /my-command for prod. I hope this clarifies.

**Comment by suavelad** [comment]
Hi @seratch ,

Thank you for the clarification 

I really appreciate it.

Lastly, I would like to paint a scenario and get guidance on how to implement it.

I sent dm  block messages to User A, User B and User C to confirm an item and once one of them confirms (User B), I will like to update the  block messages for User A and User C.

How can I achieve it .

**Comment by seratch** [comment]
To achieve your goal, your app needs to have a database to manage the "state" of confirmation. You can design it as you like, but one possible example would be to save one row in a `confirmation` table along with multiple rows in a `sent_message` table (which includes the DM's channel ID, ts, and the ID from the `confirmation` table). Once any of them is confirmed, your app can query the database and perform a `chat.update` API call for the remaining `sent_message` ones. I hope this helps you.

**Comment by suavelad** [comment]
chat.update works for block too ?. 
I will try it. 
Thank you

**Comment by suavelad** [comment]
For the chat.update, can I pass user_id as channel for slack dm conversations ?

**Comment by zimeg** [comment]
Blocks can be included in calls to `chat.update` and will overwrite existing any blocks. There's some nuance if this isn't included but blocks already exists, so going to link to [the docs](https://api.slack.com/methods/chat.update) here – check out the `blocks` argument.

A `user_id` won't work for this method, so to update a DM conversation the conversation ID of the DM will have to be used. This starts with a `D` and can be gathered from the response of a `chat.postMessage` that uses the `user_id` for a channel.
