### ISSUE TITLE
Unable to Access `app.state` with  `BoltRequest` or Use `Depends()` with slack_bolt

### ISSUE THREAD

**Issue by juan-calvo-datatonic** [slackapi/bolt-python#958]
### Description:
When integrating Slack Bolt with FastAPI, I found that Bolt's BoltRequest object does not carry FastAPI's app.state, which limits the ability to access application-wide state directly within Slack Bolt's event handlers.

Additionally, FastAPI's dependency injection mechanism, using Depends(), isn't compatible with Slack Bolt's event handlers.

Currently, I am resorting to using a global variable to pass the FastAPI Request object into Slack Bolt's event handlers as a workaround. This approach has limitations and is not ideal for a scalable, stateless cloud deployment.

### Questions:
Is there a planned feature to make BoltRequest compatible with FastAPI's app.state?
Are there plans to support FastAPI's dependency injection with Slack Bolt?
Thank you.

#### The `slack_bolt` version
`slack-bolt==1.18.0`

#### Python runtime version
`Python 3.10.11`

#### OS info
```
ProductName:            macOS
ProductVersion:         13.4.1
ProductVersionExtra:    (c)
```

### Expected result:
a) To be able to have `bolt_request.app.state`
b) To be able to use `Depends()`
```
@slack_app.event("app_mention")
def handle_mentions(body: dict, say: callable, client: WebClient, app_state=Depends(get_app_state)):
    # Now you can use app_state within this function
```

### Actual result:
a) No app in bolt_request
b) Depends() doesn't work so whatever I put on it, will not be called, and the value will be None

**Comment by seratch** [comment]
Hi @juan-calvo-datatonic, thanks for writing in. 

Since bolt-python's `App`/`AsyncApp` classes are designed to be agnostic to any third-party framework, we offer a lot of adapters to support popular frameworks like Django and FastAPI: https://github.com/slackapi/bolt-python/tree/main/slack_bolt/adapter

Almost two years ago, we received a similar feature request (https://github.com/slackapi/bolt-python/issues/542) and we've added a means to pass injected objects to bolt's middleware and listeners: https://github.com/slackapi/bolt-python/pull/544/files 

If you prefer a completely different approach, which can be a breaking change, please feel free to fork the adapter implementation for your projects. As you can see, the adapter code is pretty simple, maintaining it on your own should not cause any issues at all.

I hope this was helpful to you! If everything is clear now, would you mind closing this issue?
