### ISSUE TITLE
App installed in other workspace encounter channel_not_found with valid creds

### ISSUE THREAD

**Issue by viktor-stravito** [slackapi/bolt-python#963]
I have a slack app which works as expected when installed in the workspace where it was built. However, when this same app is installed in another workspace (even after requesting the correct permission) run into the following error

```
...
  File "/opt/python/slack_bolt/context/say/say.py", line 49, in __call__
    return self.client.chat_postMessage(
  File "/opt/python/slack_sdk/web/client.py", line 2220, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/opt/python/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/opt/python/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/opt/python/slack_sdk/web/base_client.py", line 317, in _urllib_api_call
    ).validate()
  File "/opt/python/slack_sdk/web/slack_response.py", line 199, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/chat.postMessage)
The server responded with: {'ok': False, 'error': 'channel_not_found'}
```

I've used the [tester](https://api.slack.com/methods/chat.postMessage/test) to ensure the bot has the correct access - which it seem to have given that messages sent to the same channel as in the above `say` call go through. 

Is there something obvious that I'm not understanding with the slack app installation process in another workspace? Any direction is appreciated at this point

#### The `slack_bolt` version

```
slack-bolt==1.18.0
slack-sdk==3.21.3
```

#### Python runtime version

```
Python 3.10.12
```

#### OS info

AWS Lambda Python 3.10

**Comment by seratch** [comment]
Hi @viktor-stravito, thanks for asking the question.

When you install an app into a few workspaces, your app needs to use a corresponding OAuth access token for each workspace. The "channel_not_found" error indicates that you might be using a different workspace's token to perform the API call, and that's why the channel ID could be absent in the workspace.

If you're trying to build and operate Slack's OAuth installation flow on your own, I definitely recommend starting with our examples instead:
* https://github.com/slackapi/bolt-python/blob/main/examples/oauth_app.py
* https://github.com/slackapi/bolt-python/blob/main/examples/oauth_sqlite3_app.py

When you use the built-in installation store mechanism, your app automatically chooses a valid token per workspace under the hood.

I hope this was helpful to you.
