### ISSUE TITLE
Usage of state_store

### ISSUE THREAD

**Issue by eltallerdetd** [slackapi/bolt-python#967]
Hi everyone, maybe this is a very basic question, but I am trying to understand what is state store for.

I have a created a Slack Bot with OAuth but only setting up an installation store seems to be enough for the app to retrieve the tokens I need for each workspace. I have used the S3 Bucket adapter and everything is working fine, but i really want to understand if i need to implement another bucket for the state store or if it is optional, since the app is running without problems.

I have read the documentation but i only found a brief description of what state store is; I am looking to understand what is its function, like the installation store function is to make the bot able to save and retrieve installation tokens.

Thanks in advance and sorry for this basic question.

I went through all the docs but I was unable to find an explanation that help me with this.

**Comment by seratch** [comment]
Hi @eltallerdetd, thank you for posing the question!

I advise shifting to the S3-based version. [The default one is `FileOAuthStateStore`](https://github.com/slackapi/bolt-python/blob/v1.18.0/slack_bolt/oauth/oauth_settings.py#L160-L163), which local-file-based so that it does not work with multiple app instances. Perhaps, your app is currently running on a single host, where `FileOAuthStateStore` works well. However, should you decide to expand your application to two or more server instances, the local file-based version ceases to function effectively. Not only that, when you run your app on a platform that does not allow local file access, `FileOAuthStateStore` does not work in the scenario too.

I hope this helps.
