### ISSUE TITLE
Is there a way to do an AND operation on two events?

### ISSUE THREAD

**Issue by WhyIsItSoHardToPickAUsername** [slackapi/bolt-python#978]
(Describe your issue and goal here)

I have a Slack app that will process a file shared by a user. 
So I am watching the file_shared event.
However, I don't want to process all files, just the files that have been shared AND have a particular reaction_added.
So in my file_shared event processing, how can I check if the file_shared as a reaction added to it and then only process the file?

I don't see any reaction_added information in file_shared or files_info events.
There must be some way to say:

If a file is shared AND the shared file has a particular reaction added:
  then do X
otherwise don't do anything.

#### The `slack_bolt` version

slack-bolt==1.18.0
slack-sdk==3.23.0

#### Python runtime version

Python 3.10.0
#### OS info

ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344
Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64

**Comment by seratch** [comment]
Hi @WhyIsItSoHardToPickAUsername, thanks for asking the question.

>If a file is shared AND the shared file has a particular reaction added:
then do X otherwise don't do anything.

When your app has the access to the reaction event, your app should have the access to the attached files too (the file is shared in the channel where your app's bot user is member of). So, usually I don't see the necessity to check this combination. If you need to confirm if your app has the access to a file for some reason, you can perform a `files.info` API call with the given file ID. If your app cannot access it, your API fall results in an error.

>However, I don't want to process all files, just the files that have been shared AND have a particular reaction_added.
So in my file_shared event processing, how can I check if the file_shared as a reaction added to it and then only process the file?

Generally speaking, any events from Slack's platform can be sent separately, so there is no simple way to do this type of filtering. The only approach that I can think of is that your app manages a database table to save these event deliveries, and then your app asynchronously processes only the ones associated with both events (perhaps periodically invoking this type of job would be a common approach). With that being said, this may not be a viable solution for you.

I hope this helps.

**Comment by WhyIsItSoHardToPickAUsername** [comment]
How do I get the file information of the file to which my reaction was added? I am looking at https://api.slack.com/events/reaction_added and I am not sure where to find that information:

```
{
    "type": "reaction_added",
    "user": "U123ABC456",
    "reaction": "thumbsup",
    "item_user": "U222222222",
    "item": {
        "type": "message",
        "channel": "C123ABC456",
        "ts": "1360782400.498405"
    },
    "event_ts": "1360782804.083113"
}

```

**Comment by seratch** [comment]
You can call either `conversations.history` or `conversations.replies` API with the `item.channel` and `item.ts` to fetch the message data. If the message has file attachements, you will see `attachments` property in the response.

**Comment by WhyIsItSoHardToPickAUsername** [comment]
Thank you!
