### ISSUE TITLE
What might be blocking slack listener when the slack app is served with uWSGI?

### ISSUE THREAD

**Issue by seungwonlee0603** [slackapi/bolt-python#997]
I'm working on a flask app which uses slack socket mode to listen slack messages at the same time.
The app runs fine when running as a single python process, but fails to listen to slack message when served on uWSGI.

### Reproducible in:

slack==0.0.2
slack-bolt==1.18.1
slack-sdk==3.26.0
Python 3.11.5
ProductName:    macOS
ProductVersion: 12.2.1
BuildVersion:   21D62
Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101

#### The `slack_bolt` version

slack==0.0.2
slack-bolt==1.18.1
slack-sdk==3.26.0

#### Python runtime version

Python 3.11.5

#### OS info

ProductName:    macOS
ProductVersion: 12.2.1
BuildVersion:   21D62
Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Copy this app.py and requirements.txt.
app.py
```python
import logging
from flask import Flask
from slack_bolt import App
from slack_sdk import WebClient
from slack_bolt.adapter.socket_mode import SocketModeHandler

config = {
    "SLACK_APP_TOKEN": "xapp-???",
    "SLACK_BOT_TOKEN": "xoxb-???"
}

app = Flask(__name__)

@app.route('/')
def hello():
    return 'hello world'

slack_client = WebClient(token=config["SLACK_BOT_TOKEN"])
slack_app = App(client=slack_client)

@slack_app.event("message")
def listen(event, say):
    logging.info(event)
    user = event["user"]
    text = event["text"]
    say(f"Hello <@{user}> {text}")

if __name__ == '__main__':
    try:
        logging.basicConfig(level=logging.DEBUG)

        # set up slack socket handler
        socket_handler = SocketModeHandler(
            app=slack_app, 
            app_token=config["SLACK_APP_TOKEN"]
        )
        socket_handler.connect()
        print(socket_handler)
        app.run(host='0.0.0.0', port=3000, threaded=True, debug=True)
    except Exception as e:
        logging.exception(e)

```

requirements.txt
```
blinker==1.7.0
click==8.1.7
Flask==3.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.3
slack==0.0.2
slack-bolt==1.18.1
slack-sdk==3.26.0
uWSGI==2.0.23
Werkzeug==3.0.1

```
2. Run `python app.py` and check that when you post a message on slack channel which the slack bot is invited in, the bot responds.
3. Run `uwsgi --http 127.0.0.1:3000 --master -p 4 -w app:app`, and the bot does not respond.

### Expected result:

The bot responds when the app is served with uWSGI.

### Actual result:

The bot does not respond. 

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @seungwonlee0603, thanks for asking the question. 

This is because your code initializes the Socket Mode connection within the `if __name__ == '__main__':` clause. When you start an app using uwsgi, the execution model differs from the `python app.py` command.

A quick way for initiating Socket Mode when the app is loaded is to include an option such as `--"hook-pre-app=exec:python ./start_socket_mode.py"` within the uwsgi command. You can start the Socket Mode process in the `start_socket_mode.py` code instead. However, I'm unsure about the best practices for executing graceful shutdowns while using hooks. For further insights on this, kindly refer to uwsgi's documentation and relevant forums.


In general, I don't recommend using the hooks as they may unnecessarily complicate your app deployment process. As for the Socket Mode of your app, there isn't a need to operate a web app. The Socket Mode part can be deployed separately. And even with the approach, you still can share the code with your web app side. If the reason you're trying to run the web app part is only to serve a healthcheck endpoint, I don't think you need uwsgi or similar tools just for the purpose because the healthcheck endpoint won't be public on the internet. You can simply run the Flask app like this: https://github.com/slackapi/bolt-python/blob/main/examples/socket_mode_healthcheck.py

I hope this helps.
